# Gợi ý lọc dựa trên nội dung - Phương pháp Heuristic

## Introduction

Phương pháp heuristic sẽ tìm các POI mà người dùng mục tiêu đã ghé thăm, tìm cùng danh mục, hoặc trong danh mục đó, tìm các POI mà người dùng chưa ghé thăm, và tìm các POI hàng đầu có số lượng đánh giá nhiều nhất.

Đối với mỗi POI, đếm số lần xuất hiện trong cả danh sách khu vực và danh mục.
Kết hợp các số đếm này thành một số đo duy nhất gọi là 'total_weight'. Trọng số tổng hợp này đại diện cho tần suất POI xuất hiện trên cả danh sách khu vực và danh mục. Xếp hạng các POI dựa trên tổng trọng số của chúng theo thứ tự giảm dần. Nếu tổng trọng số bằng nhau, xếp hạng sẽ dựa trên số lần xuất hiện.

Số đo này nhấn mạnh các POI thường được tìm thấy trong cả danh sách khu vực và danh mục, cho thấy mức độ liên quan hoặc tương đồng cao hơn với các POI đã đánh giá của người dùng. Hướng tiếp cận này tập trung vào tần suất xuất hiện trong các bối cảnh khác nhau (danh sách khu vực và danh mục) để ưu tiên các gợi ý.

## Điều kiện tiên quyết

Phiên bản cơ sở dữ liệu `neo4j` phải đã được khởi tạo và điền dữ liệu.

Thông tin kết nối `HOST`, `DATABASE` và `PASSWORD` phải được lưu trữ trong `NEO4J_CONF_FILE` để thiết lập kết nối tới cơ sở dữ liệu neo4j.

Sử dụng `neo4j python driver` để truy vấn cơ sở dữ liệu neo4j.

Sử dụng truy vấn `Cypher` để tạo các gợi ý.

In [33]:
import os
import configparser
import textwrap
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from neo4j import GraphDatabase

In [34]:
# Sử dụng file ini cho thông tin đăng nhập, nếu không sử dụng mặc định
HOST = 'neo4j://localhost'
DATABASE = 'neo4j'
PASSWORD = 'password'

NEO4J_CONF_FILE = 'neo4j.ini'

if NEO4J_CONF_FILE is not None and os.path.exists(NEO4J_CONF_FILE):
    config = configparser.RawConfigParser()
    config.read(NEO4J_CONF_FILE)
    HOST = config['NEO4J']['HOST']
    DATABASE = config['NEO4J'].get('DATABASE', 'neo4j')
    USERNAME = config['NEO4J'].get('USERNAME', DATABASE)
    PASSWORD = config['NEO4J']['PASSWORD']
    print('Using custom database properties')
else:
    print('Could not find database properties file, using defaults')


# Kết nối bằng neo4j python driver
driver = GraphDatabase.driver(HOST, auth=(USERNAME, PASSWORD))

Using custom database properties

In [35]:
# Hàm trợ giúp (helper)
def run(driver, query, params=None):
    with driver.session(database=DATABASE) as session:
        if params is not None:
            return [r for r in session.run(query, params)]
        else:
            return [r for r in session.run(query)]

## Gợi ý bằng Heuristic

Dựa trên POI mà người dùng đã đánh giá trước đó, gợi ý các POI khác trong cùng danh mục hoặc khu vực.

In [36]:
# HÀM: Tạo gợi ý dựa trên phương pháp Lọc dựa trên nội dung - Heuristic
# INPUT: user_id, poi_id
# OUTPUT: dataframe[user_id, poi_id, rec_poi_id, rec_poi_name]


# Thực nghiệm lần 1:
# Precision Score: 0.01268724954952532
# Recall Score: 1.0
# Coverage Score: 0.5375284306292646
# F1 Score: 0.02505659976 

# => Bổ sung {k}, chỉ lấy top {k} poi gợi ý thay vì lấy toàn bộ để cải thiện precision và F1 Score

# Thực nghiệm lần 2 (k = 5):
# Precision Score: 0.22285714285714286
# Recall Score: 0.06200317965023847
# Coverage Score: 0.0401819560272934
# F1 Score: 0.09701492537313432

# Thực nghiệm lần 3 (k = 10):
# Precision Score: 0.1838095238095238
# Recall Score: 0.10227874933757286
# Coverage Score: 0.06557998483699773
# F1 Score: 0.13142662580864828

# Crawl lại bộ dữ liệu lần 2 (Bổ sung field description)
# Thực nghiệm lần 1:
# Precision Score: 0.01442657281638114
# Recall Score: 0.6850828729281768
# Coverage Score: 0.3851473241130487
# F1 Score: 0.02825808289417462

# Thực nghiệm lần 2 (k = 5):
# Precision Score: 0.09230769230769231
# Recall Score: 0.03314917127071823
# Coverage Score: 0.03096812988574865
# F1 Score: 0.048780487804878044

# Thực nghiệm lần 3 (k = 10):
# Precision Score: 0.07788461538461539
# Recall Score: 0.05593922651933702
# Coverage Score: 0.04720384846662658
# F1 Score: 0.06511254019292605

# Thực nghiệm lần 4 (k = 10, bổ sung tọa độ để gợi ý địa điểm lân cận):
# Precision Score: 0.08557692307692308
# Recall Score: 0.06146408839779006
# Coverage Score: 0.059230306674684305
# F1 Score: 0.07154340836012862

def heuristic_recommendation(user_id, poi_id, k=10):
    # Lấy các POI trong cùng khu vực với POI đã được người dùng đánh giá
    records_region = run(driver, textwrap.dedent("""\
        MATCH (user {id: $user_id})-[:REVIEWED]->(poi:Poi {id: $poi_id})-[:LOCATED_AT]->(region:Region)<-[:LOCATED_AT]-(other_poi:Poi)<-[rated:RATED]-(review:Review)
        WHERE poi <> other_poi
        WITH user, poi, other_poi, region, count(DISTINCT rated) AS num_reviews
        RETURN user.id AS user_id, poi.id AS poi_id, other_poi.id AS rec_poi_id, other_poi.name AS rec_poi_name, region.name AS region, num_reviews AS occurrences
        """),
        params = {'user_id': user_id, 'poi_id': poi_id}
    )
    print(f"Tìm thấy {len(records_region)} records POI có CÙNG KHU VỰC.")
    # Lấy các POI trong cùng danh mục với POI đã được người dùng đánh giá 
    records_category = run(driver, textwrap.dedent("""\
        MATCH (user {id: $user_id})-[:REVIEWED]->(poi:Poi {id: $poi_id})-[:BELONGS_TO]->(category:Category)<-[:BELONGS_TO]-(other_poi:Poi)<-[rated:RATED]-(review:Review)
        WHERE poi <> other_poi
        WITH user, poi, other_poi, category, count(DISTINCT rated) AS num_reviews
        RETURN user.id AS user_id, poi.id AS poi_id, other_poi.id AS rec_poi_id, other_poi.name AS rec_poi_name, category.name AS category_name, num_reviews AS occurrences
        """),
        params = {'user_id': user_id, 'poi_id': poi_id}
    )
    print(f"Tìm thấy {len(records_category)} records POI có CÙNG DANH MỤC.")
    # Lấy các POI lân cận (NEARBY - trong bán kính 1.5km)
    records_nearby = run(driver, textwrap.dedent("""\
        MATCH (user {id: $user_id})-[:REVIEWED]->(poi:Poi {id: $poi_id})-[n:NEARBY]->(other_poi:Poi)<-[rated:RATED]-(review:Review)
        WHERE poi <> other_poi
        WITH user, poi, other_poi, n.distance_km AS distance, count(DISTINCT rated) AS num_reviews
        RETURN user.id AS user_id, poi.id AS poi_id, other_poi.id AS rec_poi_id, other_poi.name AS rec_poi_name, distance, num_reviews AS occurrences
        """),
        params = {'user_id': user_id, 'poi_id': poi_id}
    )
    print(f"Tìm thấy {len(records_nearby)} records POI LÂN CẬN (< 1.5km).")
    
    
    # Convert kết quả sang DataFrame và gom nhóm tính trọng số (weight)
    if records_region:
        df_records_region = pd.DataFrame([dict(record) for record in records_region])
        # Group by 'poi_id', 'poi_name', and 'occurrences', then aggregate the count of occurrences
        df_records_region_agg = df_records_region.groupby(['user_id', 'poi_id', 'rec_poi_id', 'rec_poi_name', 'occurrences']).size().reset_index(name='weight_region')
        print(f"[Khu vực] Rút gọn còn {len(df_records_region_agg)} records sau khi gom nhóm.")
    else:
        df_records_region_agg = pd.DataFrame(columns=['user_id', 'poi_id', 'rec_poi_id', 'rec_poi_name', 'occurrences', 'weight_region'])
        print(f"[Khu vực] Không tìm thấy record nào.")

    if records_category:
        df_records_category = pd.DataFrame([dict(record) for record in records_category])
        # Group by 'poi_id', 'poi_name', and 'occurrences', then aggregate the count of occurrences
        df_records_category_agg = df_records_category.groupby(['user_id', 'poi_id', 'rec_poi_id', 'rec_poi_name', 'occurrences']).size().reset_index(name='weight_category')
        print(f" [Danh mục] Rút gọn còn {len(df_records_category_agg)} records (tính trùng lặp thể loại).")
    else:
       df_records_category_agg = pd.DataFrame(columns=['user_id', 'poi_id', 'rec_poi_id', 'rec_poi_name', 'occurrences', 'weight_category'])
       print(f"[Danh mục] Không tìm thấy record nào.")
    if records_nearby:
        df_nearby = pd.DataFrame([dict(r) for r in records_nearby])
        df_nearby_agg = df_nearby.groupby(['user_id', 'poi_id', 'rec_poi_id', 'rec_poi_name', 'occurrences']).size().reset_index(name='weight_nearby')
    else:
        df_nearby_agg = pd.DataFrame(columns=['user_id', 'poi_id', 'rec_poi_id', 'rec_poi_name', 'occurrences', 'weight_nearby'])
    

    df_records_region_agg.rename(columns={'user_id': 'user_id_region', 'poi_id': 'poi_id_region', 'occurrences': 'occurrences_region'}, inplace=True)
    df_records_category_agg.rename(columns={'user_id': 'user_id_category', 'poi_id': 'poi_id_category', 'occurrences': 'occurrences_category'}, inplace=True)
    df_nearby_agg.rename(columns={'user_id': 'user_id_nearby', 'poi_id': 'poi_id_nearby', 'occurrences': 'occurrences_nearby'}, inplace=True)

    # Tính tần suất xuất hiện của POI trong cả hai danh sách
    # Gộp DataFrame dựa trên 'rec_poi_id'
    recommended_interactions = pd.merge(df_records_region_agg, df_records_category_agg, on=['rec_poi_id', 'rec_poi_name'], suffixes=('_region', '_category'), how='outer')
    recommended_interactions = pd.merge(recommended_interactions, df_nearby_agg, on=['rec_poi_id', 'rec_poi_name'], suffixes=('', '_nearby'), how='outer')
    print(f"Gộp 3 danh sách (Outer Join): Tổng cộng có {len(recommended_interactions)} records.")

     # Điền giá trị fallback cho user_id, poi_id, occurrences
    recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
    recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
    recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)

    # Điền các giá trị NaN bằng 0 cho các cột 'weight'
    recommended_interactions['weight_region'] = recommended_interactions['weight_region'].fillna(0)
    recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)
    recommended_interactions['weight_nearby'] = recommended_interactions['weight_nearby'].fillna(0)

    print(f"Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: {len(recommended_interactions)}")
    
    # Cộng các cột 'weight' để tính tổng trọng số
    recommended_interactions['total_weight'] = recommended_interactions['weight_region'] + recommended_interactions['weight_category'] + recommended_interactions['weight_nearby']

    # Loại bỏ các cột 'weight' riêng lẻ nếu cần
    recommended_interactions.drop(['user_id_category', 'user_id_nearby', 
                                    'poi_id_category', 'poi_id_nearby', 
                                    'occurrences_category', 'occurrences_nearby', 
                                    'weight_region', 'weight_category', 'weight_nearby'], axis=1, inplace=True, errors='ignore')
    # Sắp xếp DataFrame theo 'total_weight' giảm dần, sau đó theo 'occurrences'
    recommended_interactions = recommended_interactions.sort_values(by=['total_weight', 'occurrences'], ascending=[False, False])

     # In ra Top 5 địa điểm được đề xuất hàng đầu
    print(f"*** Top {k} địa điểm được khuyến nghị:")
    for idx, row in recommended_interactions.head(k).iterrows():
        print(f"      - Hạng {idx+1}: POI ID = {row['rec_poi_id']} | Tên POI = {row['rec_poi_name']} | (Total Weight: {row['total_weight']}, Số reviews toàn cục: {row['occurrences']})")


    # Khởi tạo lại chỉ mục cho DataFrame
    recommended_interactions.reset_index(drop=True, inplace=True)
    # Sắp xếp lại các cột
    recommended_interactions = recommended_interactions[['user_id', 'poi_id', 'rec_poi_id', 'rec_poi_name']]
    # Loại bỏ trùng lặp
    recommended_interactions = recommended_interactions.drop_duplicates()

    # Hiển thị DataFrame đã gộp
    return recommended_interactions.head(k)

In [37]:
# ID của người dùng mục tiêu
user_id = 371
# ID của POI mục tiêu
poi_id = 7171779

df_recommend = heuristic_recommendation(user_id, poi_id)

df_recommend

Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 28 records POI có CÙNG DANH MỤC.
Tìm thấy 615 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 28 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 720 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 720
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 419: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 3.0, Số reviews toàn cục: 109.0)
      - Hạng 50: POI ID = 2273094 | Tên POI = Công Ty Tnhh Du Lịch Việt Vui | (Total Weight: 3.0, Số reviews toàn cục: 94.0)
      - Hạng 170: POI ID = 7194403 | Tên POI = Ginkgo Voyage Private Day Tours | (Total Weight: 3.0, Số reviews toàn cục: 49.0)
      - Hạng 491: POI ID = 19163793 | Tên POI = 102 Saigonese | (Total Weight: 3.0, Số reviews toàn cục: 5.0)
      - Hạng 435: POI ID = 16666055 | Tên POI = Trang Thanh Travel | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 38: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 246: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 532: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 113: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)

   user_id     poi_id  rec_poi_id                     rec_poi_name
0    371.0  7171779.0    15528737                 HANA TOURIST VIP
1    371.0  7171779.0     2273094    Công Ty Tnhh Du Lịch Việt Vui
2    371.0  7171779.0     7194403  Ginkgo Voyage Private Day Tours
3    371.0  7171779.0    19163793                    102 Saigonese
4    371.0  7171779.0    16666055               Trang Thanh Travel
5    371.0  7171779.0     2004786                 Vespa Adventures
6    371.0  7171779.0    10005057             Ben Nghe Street Food
7    371.0  7171779.0    24162332      Monkee Shisha Lounge Saigon
8    371.0  7171779.0      311087                 Chợ Bến Thành
9    371.0  7171779.0     5505885                   Đường Bùi Viện

# Đánh giá

In [38]:
# DataFrame các POI
pois = run(driver, textwrap.dedent("""\
    MATCH (poi:Poi)
    RETURN poi.id
    """),
    params = {}
)

df_pois = pd.DataFrame([r.data() for r in pois])
df_pois

        poi.id
0       311103
1      2005826
2       311087
3      4542125
4       311089
...        ...
3321  34509929
3322  34508995
3323  34515006
3324  34435391
3325  34464291

[3326 rows x 1 columns]

In [39]:
# DataFrame các đánh giá

reviews = run(driver, textwrap.dedent("""\
    MATCH (user:User)-[review:REVIEWED]->(poi:Poi)
    RETURN user.id AS user_id, poi.id AS poi_id
    """),
    params = {}
)

df_reviews = pd.DataFrame([r.data() for r in reviews])
df_reviews

       user_id    poi_id
0            1    311103
1            2    311103
2            3    311103
3            4    311103
4            5    311103
...        ...       ...
23943    21311  15129760
23944    21312  15129760
23945    21313  15129760
23946    21314  15129760
23947    21315  34514717

[23948 rows x 2 columns]

In [40]:
# Nhóm theo 'user_id' và đếm số lần xuất hiện
user_counts = df_reviews.groupby('user_id').size()

# Lọc ra các người dùng có ít hơn 5 lần xuất hiện
valid_users = user_counts[user_counts >= 5].index

# Lọc DataFrame gốc dựa trên danh sách người dùng hợp lệ
filtered_df_reviews = df_reviews[df_reviews['user_id'].isin(valid_users)].copy()
filtered_df_reviews

       user_id    poi_id
50          51    311103
51          52    311103
103        104    311103
116        117    311103
118        119    311103
...        ...       ...
23570      481  12829864
23571     1303  12829864
23573     2886  12829864
23613     1246   9974597
23714     1004  15129760

[1038 rows x 2 columns]

In [41]:
# Chia tập dữ liệu thành 90% tập huấn luyện (training) và 10% tập kiểm tra (test)
df_train, df_test = train_test_split(filtered_df_reviews, test_size=0.1, random_state=100)

df_train

       user_id    poi_id
23463      181   9806390
2694       473    311094
3279      1177   1910195
2331      1334  10836601
8110        51  16657089
...        ...       ...
4403       284    311092
555        493   4542125
2215      1459   4552853
745         52   2037764
4354       473   2385857

[934 rows x 2 columns]

In [42]:
df_test

       user_id    poi_id
3284      1253   1910195
5049       683    552637
14873      606  10044301
1854       472    317896
2336      1415  10836601
...        ...       ...
1378      1006  10005057
23298      181  10388517
23338      474   1809055
545        484    311087
1681       313   8290115

[104 rows x 2 columns]

In [43]:
# Lấy gợi ý cho từng dòng trong tập test
df_all_retrieved = pd.DataFrame()
for index, row in df_test.iterrows():
    recommended_interactions = heuristic_recommendation(row['user_id'], row['poi_id'])
    # Nối các tương tác gợi ý với test_recommendations
    df_all_retrieved = pd.concat([df_all_retrieved, recommended_interactions], ignore_index=True)

# Loại bỏ các cột trùng lặp
df_all_retrieved = df_all_retrieved.drop_duplicates()

df_all_retrieved

Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 586 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1008 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1008
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 155: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 56: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 149: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 547: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 173: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 486: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 210: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 12 records POI có CÙNG DANH MỤC.
Tìm thấy 345 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 12 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 994 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 994
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 318: POI ID = 10085046 | Tên POI = Nhà thờ Tân Định | (Total Weight: 3.0, Số reviews toàn cục: 53.0)
      - Hạng 242: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 2.0, Số reviews toàn cục: 1015.0)
      - Hạng 208: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 2.0, Số reviews toàn cục: 380.0)
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 546: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 6: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 173: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 108: POI ID = 3948543 | Tên POI = Saigon Hotpot - Travel With Local Youth | (Total Weight: 2.0, Số reviews toàn cục: 144.0)
      - Hạng 2: POI ID = 311089 | Tên POI = Bưu điện trung tâm Sài Gòn | (Total Weight: 2.0, Số reviews toàn cục: 139.0)
      - Hạng 276: POI ID = 8775058 | Tên POI = Saigon On Motorbike | (Total Weight: 2.0, Số reviews toàn cục: 128.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 6 records POI có CÙNG DANH MỤC.
Tìm thấy 24 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 6 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 824 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 824
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 355: POI ID = 12511664 | Tên POI = Thành Bưởi | (Total Weight: 3.0, Số reviews toàn cục: 21.0)
      - Hạng 451: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 242: POI ID = 8869748 | Tên POI = Vinasun Taxi | (Total Weight: 2.0, Số reviews toàn cục: 79.0)
      - Hạng 464: POI ID = 15300685 | Tên POI = Kumho Samco Buslines | (Total Weight: 2.0, Số reviews toàn cục: 73.0)
      - Hạng 64: POI ID = 2273335 | Tên POI = Chùa Bà Thiên Hậu | (Total Weight: 2.0, Số reviews toàn cục: 69.0)
      - Hạng 665: POI ID = 27130109 | Tên POI = Master Escape | (Total Weight: 2.0, Số reviews toàn cục: 40.0)
      - Hạng 413: POI ID = 13957334 | Tên POI = Vietnam Silver House | (Total Weight: 2.0, Số reviews toàn cục: 35.0)
      - Hạng 412: POI ID = 13934245 | Tên POI = Mon Amie Tailor - Best Tailor in HCMC | (Total Weight: 2.0, Số reviews toàn cục: 30.0)
      - Hạng 11: POI ID = 454972 | Tên POI = Phố Tàu Sài Gòn (Chợ Lớn Quận 5) | (Total Weight: 2.0, Số reviews toàn cục: 28.0)
      - Hạng 186: POI ID = 7907864 | Tên POI = Chua Van Phat - Temple of Ten Thousand Buddhas | (Total Weight: 2.0, Số reviews toàn cục: 23.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 0 records POI có CÙNG DANH MỤC.
Tìm thấy 587 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
[Danh mục] Không tìm thấy record nào.
Gộp 3 danh sách (Outer Join): Tổng cộng có 1001 records.

C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:121: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:122: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)

Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1001
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 157: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 151: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 541: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 6: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 175: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 480: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 41: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 212: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 69: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 579 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 996 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 996
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 158: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 58: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 152: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 539: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 6: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 479: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 42: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 212: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 70: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 43: POI ID = 1752815 | Tên POI = Saigon Saigon Rooftop Bar | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 587 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1002 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1002
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 247: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 3.0, Số reviews toàn cục: 155.0)
      - Hạng 43: POI ID = 1784754 | Tên POI = Đường Đồng Khởi | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 890: POI ID = 32800829 | Tên POI = The Laundry + Rooftop Bar & Cafe | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 158: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 152: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 542: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 6: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 176: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 56: POI ID = 2005826 | Tên POI = Cu Chi Tunnels | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 12 records POI có CÙNG DANH MỤC.
Tìm thấy 182 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 12 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 879 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 879
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 76: POI ID = 2385857 | Tên POI = Chua Vinh Nghiem | (Total Weight: 3.0, Số reviews toàn cục: 20.0)
      - Hạng 21: POI ID = 552637 | Tên POI = Temple of the Buddha's Relic (Xa Loi pagoda) | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
      - Hạng 219: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 2.0, Số reviews toàn cục: 1015.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 106: POI ID = 3948543 | Tên POI = Saigon Hotpot - Travel With Local Youth | (Total Weight: 2.0, Số reviews toàn cục: 144.0)
      - Hạng 1: POI ID = 311089 | Tên POI = Bưu điện trung tâm Sài Gòn | (Total Weight: 2.0, Số reviews toàn cục: 139.0)
      - Hạng 11: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 2.0, Số reviews toàn cục: 126.0)
      - Hạng 10: POI ID = 317896 | Tên POI = Nhà thờ Đức Bà Sài Gòn | (Total Weight: 2.0, Số reviews toàn cục: 118.0)
      - Hạng 299: POI ID = 10836601 | Tên POI = Đường Sách Nguyễn Văn Bình | (Total Weight: 2.0, Số reviews toàn cục: 113.0)
      - Hạng 531: POI ID = 17379413 | Tên POI = Heritage Line - Refined Waterway Voyages | (Total Weight: 2.0, Số reviews toàn cục: 106.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 482 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 561 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 561
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 2273343 | Tên POI = Phạm Ngũ Lão | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 118: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 24: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 177: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 401: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 144: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 312: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 81: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 7 records POI có CÙNG DANH MỤC.
Tìm thấy 606 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 7 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1047 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1047
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 84: POI ID = 2414430 | Tên POI = Công Viên Tao Đàn | (Total Weight: 3.0, Số reviews toàn cục: 52.0)
      - Hạng 81: POI ID = 2357145 | Tên POI = Cong Vien 23 Thang 9 | (Total Weight: 3.0, Số reviews toàn cục: 15.0)
      - Hạng 221: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 2.0, Số reviews toàn cục: 380.0)
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 164: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 155: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 573: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 4: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 184: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 0 records POI có CÙNG DANH MỤC.
Tìm thấy 414 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
[Danh mục] Không tìm thấy record nào.
Gộp 3 danh sách (Outer Join): Tổng cộng có 1051 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1051
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 223: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 2.0, Số reviews toàn cục: 380.0)
      - Hạng 58: POI ID = 2044621 | Tên POI = XO Tours | (Total Weight: 2.0, Số reviews toàn cục: 360.0)
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 576: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 184: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 114: POI ID = 3948543 | Tên POI = Saigon Hotpot - Travel With Local Youth | (Total Weight: 2.0, Số reviews toàn cục: 144.0)
      - Hạng 291: POI ID = 8775058 | Tên POI = Saigon On Motorbike | (Total Weight: 2.0, Số reviews toàn cục: 128.0)
      - Hạng 337: POI ID = 10117391 | Tên POI = Street Food Man | (Total Weight: 2.0, Số reviews toàn cục: 114.0)
      - Hạng 535: POI ID = 14025887 | Tên POI = The Privé Spa | International Lash, Nail Care & Spa | Ben Thanh (D1) | (Total Weight: 2.0, Số reviews toàn cục: 97.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 2 records POI có CÙNG DANH MỤC.
Tìm thấy 51 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 2 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 825 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 825
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 204: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 2.0, Số reviews toàn cục: 1015.0)
      - Hạng 50: POI ID = 2044621 | Tên POI = XO Tours | (Total Weight: 2.0, Số reviews toàn cục: 360.0)
      - Hạng 232: POI ID = 8775058 | Tên POI = Saigon On Motorbike | (Total Weight: 2.0, Số reviews toàn cục: 128.0)
      - Hạng 268: POI ID = 10117391 | Tên POI = Street Food Man | (Total Weight: 2.0, Số reviews toàn cục: 114.0)
      - Hạng 338: POI ID = 12204583 | Tên POI = Tour With Xuan | (Total Weight: 2.0, Số reviews toàn cục: 61.0)
      - Hạng 55: POI ID = 2168911 | Tên POI = Ho Chi Minh City Museum | (Total Weight: 2.0, Số reviews toàn cục: 47.0)
      - Hạng 339: POI ID = 12226320 | Tên POI = Tour Guide In Saigon | (Total Weight: 2.0, Số reviews toàn cục: 36.0)
      - Hạng 484: POI ID = 16694960 | Tên POI = Tâm Therapy | (Total Weight: 2.0, Số reviews toàn cục: 24.0)
      - Hạng 713: POI ID = 28454178 | Tên POI = Emes Escape Room | (Total Weight: 2.0, Số reviews toàn cục: 22.0)
      - Hạng 638: POI ID = 25973054 | Tên POI = Real Escape Sài Gòn | (Total Weight: 2.0, Số reviews toàn cục: 20.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 386 records POI có CÙNG DANH MỤC.
Tìm thấy 423 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 386 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 733 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 733

C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:121: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:122: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)

*** Top 10 địa điểm được khuyến nghị:
      - Hạng 80: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 3.0, Số reviews toàn cục: 101.0)
      - Hạng 240: POI ID = 11899009 | Tên POI = Coco Care Spa | (Total Weight: 3.0, Số reviews toàn cục: 47.0)
      - Hạng 33: POI ID = 2334935 | Tên POI = Foot Massage Salon Quỳnh Như 137 | (Total Weight: 3.0, Số reviews toàn cục: 45.0)
      - Hạng 192: POI ID = 10767864 | Tên POI = Rocky Spa | (Total Weight: 3.0, Số reviews toàn cục: 43.0)
      - Hạng 324: POI ID = 14116019 | Tên POI = Zen Spa - Foot & Body Massage | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 608: POI ID = 28029827 | Tên POI = Bông Spa (Branch Nguyen Canh Chan) | (Total Weight: 3.0, Số reviews toàn cục: 27.0)
      - Hạng 733: POI ID = 34495164 | Tên POI = NAP Healing & Wellness | (Total Weight: 3.0, Số reviews toàn cục: 25.0)
      - Hạng 53: POI ID = 2726268 | Tên POI = Cat Moc Spa | (Total Weight: 3.0, Số reviews toàn cục: 22.0)
      - Hạng 183: POI ID = 9974597 | Tên POI = Liberty Spa | (Total Weight: 3.0, Số reviews toàn cục: 19.0)
      - Hạng 113: POI ID = 6983488 | Tên POI = Kim Spa | (Total Weight: 3.0, Số reviews toàn cục: 14.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 510 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 995 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 995
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 705: POI ID = 21230453 | Tên POI = Saigon Skydeck | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 155: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 149: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 540: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 173: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 481: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 208: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 68: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 482 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 561 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 561
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 2273343 | Tên POI = Phạm Ngũ Lão | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 118: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 24: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 177: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 401: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 144: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 312: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 81: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 2 records POI có CÙNG DANH MỤC.
Tìm thấy 24 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 2 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 839 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 839
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 209: POI ID = 8300005 | Tên POI = Cầu Ánh Sao | (Total Weight: 2.0, Số reviews toàn cục: 16.0)
      - Hạng 258: POI ID = 9882201 | Tên POI = Anna Sanctuary Wellness Spa | (Total Weight: 2.0, Số reviews toàn cục: 8.0)
      - Hạng 117: POI ID = 4773063 | Tên POI = Body by Jovie | (Total Weight: 2.0, Số reviews toàn cục: 7.0)
      - Hạng 208: POI ID = 8295665 | Tên POI = Trung Tâm Hội Chợ Và Triển Lãm Sài Gòn - Secc | (Total Weight: 2.0, Số reviews toàn cục: 7.0)
      - Hạng 201: POI ID = 8181417 | Tên POI = Chợ Tân Mỹ | (Total Weight: 2.0, Số reviews toàn cục: 5.0)
      - Hạng 316: POI ID = 11741470 | Tên POI = Massage Người Khiếm Thị Ánh Dương 2 | (Total Weight: 2.0, Số reviews toàn cục: 3.0)
      - Hạng 394: POI ID = 13217248 | Tên POI = Kart1 | (Total Weight: 2.0, Số reviews toàn cục: 3.0)
      - Hạng 812: POI ID = 33712421 | Tên POI = Oriental Retreat Spa & Wellness | (Total Weight: 2.0, Số reviews toàn cục: 2.0)
      - Hạng 555: POI ID = 18978667 | Tên POI = Halulu Nail | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 804: POI ID = 33358764 | Tên POI = Hey Jack Spa | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 5 records POI có CÙNG DANH MỤC.
Tìm thấy 277 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 5 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 856 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 856
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 27: POI ID = 1368412 | Tên POI = Ton Duc Thang Museum | (Total Weight: 3.0, Số reviews toàn cục: 39.0)
      - Hạng 614: POI ID = 23300698 | Tên POI = Euphorea Salon And Spa - Bason Branch | (Total Weight: 2.0, Số reviews toàn cục: 302.0)
      - Hạng 133: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 412: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 35: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 182: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 63: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 36: POI ID = 1752815 | Tên POI = Saigon Saigon Rooftop Bar | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 99: POI ID = 3948543 | Tên POI = Saigon Hotpot - Travel With Local Youth | (Total Weight: 2.0, Số reviews toàn cục: 144.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 142 records POI có CÙNG DANH MỤC.
Tìm thấy 568 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 142 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1039 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1039
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 141: POI ID = 4881460 | Tên POI = Nhà May Phạm Minh | (Total Weight: 3.0, Số reviews toàn cục: 53.0)
      - Hạng 196: POI ID = 6994939 | Tên POI = Thuy Design House | (Total Weight: 3.0, Số reviews toàn cục: 49.0)
      - Hạng 172: POI ID = 6601902 | Tên POI = Shimmer Silver | (Total Weight: 3.0, Số reviews toàn cục: 48.0)
      - Hạng 302: POI ID = 9563623 | Tên POI = Veritas Bespoke | (Total Weight: 3.0, Số reviews toàn cục: 43.0)
      - Hạng 453: POI ID = 12600679 | Tên POI = Metiseko - Saigon | (Total Weight: 3.0, Số reviews toàn cục: 42.0)
      - Hạng 334: POI ID = 10525874 | Tên POI = Nhà may Tuyển Tailor's | (Total Weight: 3.0, Số reviews toàn cục: 40.0)
      - Hạng 135: POI ID = 4771094 | Tên POI = Viet Thanh Silk - Tailor | (Total Weight: 3.0, Số reviews toàn cục: 22.0)
      - Hạng 746: POI ID = 24001941 | Tên POI = Cây Đầu To | (Total Weight: 3.0, Số reviews toàn cục: 21.0)
      - Hạng 847: POI ID = 27296727 | Tên POI = Amaï Dong Khoi | (Total Weight: 3.0, Số reviews toàn cục: 18.0)
      - Hạng 191: POI ID = 6963268 | Tên POI = Artbook | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 10 records POI có CÙNG DANH MỤC.
Tìm thấy 626 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 10 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 734 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 734
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 164.0)
      - Hạng 318: POI ID = 12084531 | Tên POI = Chợ Đêm Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 46.0)
      - Hạng 75: POI ID = 2484797 | Tên POI = Dan Sinh Market | (Total Weight: 3.0, Số reviews toàn cục: 12.0)
      - Hạng 602: POI ID = 26899566 | Tên POI = Central Market 23.9 | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 173: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 43: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 541: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 222: POI ID = 8599407 | Tên POI = Saigon Adventure | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 117: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 7: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 6 records POI có CÙNG DANH MỤC.
Tìm thấy 410 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 6 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 913 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 913
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 831: POI ID = 33056335 | Tên POI = Elite Of Saigon: A Luxurious Dining Cruise Experience | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 651: POI ID = 23300698 | Tên POI = Euphorea Salon And Spa - Bason Branch | (Total Weight: 2.0, Số reviews toàn cục: 302.0)
      - Hạng 147: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 54: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 141: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 447: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 38: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 197: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 66: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 39: POI ID = 1752815 | Tên POI = Saigon Saigon Rooftop Bar | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 576 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 660 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 660
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 150: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 33: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 225: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 486: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 101: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 7: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 388: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 102: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
      - Hạng 43: POI ID = 2273094 | Tên POI = Công Ty Tnhh Du Lịch Việt Vui | (Total Weight: 2.0, Số reviews toàn cục: 94.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 75 records POI có CÙNG DANH MỤC.
Tìm thấy 584 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 75 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1016 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1016
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 78: POI ID = 2336225 | Tên POI = Skybar thư giãn | (Total Weight: 3.0, Số reviews toàn cục: 59.0)
      - Hạng 195: POI ID = 7109031 | Tên POI = Apocalypse Now Bar | (Total Weight: 3.0, Số reviews toàn cục: 34.0)
      - Hạng 539: POI ID = 14947946 | Tên POI = SKYXX | (Total Weight: 3.0, Số reviews toàn cục: 26.0)
      - Hạng 108: POI ID = 3815598 | Tên POI = Broma Not A Bar | (Total Weight: 3.0, Số reviews toàn cục: 21.0)
      - Hạng 156: POI ID = 6364047 | Tên POI = Lush | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
      - Hạng 255: POI ID = 8432743 | Tên POI = Thi Bar | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
      - Hạng 300: POI ID = 9754920 | Tên POI = Snuffbox Speakeasy Cocktails Bar | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
      - Hạng 391: POI ID = 11872607 | Tên POI = ENVY Club | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
      - Hạng 746: POI ID = 25009311 | Tên POI = The Blinders Cocktail Bar | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
      - Hạng 65: POI ID = 2218023 | Tên POI = Yoko Cafe | (Total Weight: 3.0, Số reviews toàn cục: 14.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 0 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 825 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 825
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 48: POI ID = 2005826 | Tên POI = Cu Chi Tunnels | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 207: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 8: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 2.0, Số reviews toàn cục: 126.0)
      - Hạng 35: POI ID = 1784754 | Tên POI = Đường Đồng Khởi | (Total Weight: 2.0, Số reviews toàn cục: 41.0)
      - Hạng 113: POI ID = 4597843 | Tên POI = Binh Quoi Village | (Total Weight: 2.0, Số reviews toàn cục: 25.0)
      - Hạng 111: POI ID = 4559699 | Tên POI = Rung Sac Military Base | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 736: POI ID = 32800829 | Tên POI = The Laundry + Rooftop Bar & Cafe | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 205: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 1.0, Số reviews toàn cục: 1015.0)
      - Hạng 175: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 1.0, Số reviews toàn cục: 380.0)
      - Hạng 50: POI ID = 2044621 | Tên POI = XO Tours | (Total Weight: 1.0, Số reviews toàn cục: 360.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 292 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 852 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 852
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 612: POI ID = 23300698 | Tên POI = Euphorea Salon And Spa - Bason Branch | (Total Weight: 2.0, Số reviews toàn cục: 302.0)
      - Hạng 132: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 411: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 34: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 181: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 62: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 35: POI ID = 1752815 | Tên POI = Saigon Saigon Rooftop Bar | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 98: POI ID = 3948543 | Tên POI = Saigon Hotpot - Travel With Local Youth | (Total Weight: 2.0, Số reviews toàn cục: 144.0)
      - Hạng 1: POI ID = 311089 | Tên POI = Bưu điện trung tâm Sài Gòn | (Total Weight: 2.0, Số reviews toàn cục: 139.0)
      - Hạng 96: POI ID = 3749935 | Tên POI = Saigon Heritage Spa | (Total Weight: 2.0, Số reviews toàn cục: 128.0)

C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:127: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_nearby'] = recommended_interactions['weight_nearby'].fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:127: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_nearby'] = recommended_interactions['weight_nearby'].fillna(0)

Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 0 records POI có CÙNG DANH MỤC.
Tìm thấy 0 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
[Danh mục] Không tìm thấy record nào.
Gộp 3 danh sách (Outer Join): Tổng cộng có 823 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 823
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 203: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 1, Số reviews toàn cục: 1015)
      - Hạng 173: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 1, Số reviews toàn cục: 380)
      - Hạng 50: POI ID = 2044621 | Tên POI = XO Tours | (Total Weight: 1, Số reviews toàn cục: 360)
      - Hạng 262: POI ID = 10044301 | Tên POI = Công ty cổ phần xe khách Phương Trang | (Total Weight: 1, Số reviews toàn cục: 318)
      - Hạng 118: POI ID = 4795476 | Tên POI = Phan's Custom Tailor | (Total Weight: 1, Số reviews toàn cục: 310)
      - Hạng 592: POI ID = 23300698 | Tên POI = Euphorea Salon And Spa - Bason Branch | (Total Weight: 1, Số reviews toàn cục: 302)
      - Hạng 30: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 1, Số reviews toàn cục: 294)
      - Hạng 132: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 1, Số reviews toàn cục: 294)
      - Hạng 49: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 1, Số reviews toàn cục: 287)
      - Hạng 127: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 1, Số reviews toàn cục: 270)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 75 records POI có CÙNG DANH MỤC.
Tìm thấy 432 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 75 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 931 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 931
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 76: POI ID = 2336225 | Tên POI = Skybar thư giãn | (Total Weight: 3.0, Số reviews toàn cục: 59.0)
      - Hạng 17: POI ID = 455410 | Tên POI = Rex Hotel Rooftop Bar | (Total Weight: 3.0, Số reviews toàn cục: 31.0)
      - Hạng 500: POI ID = 14947946 | Tên POI = SKYXX | (Total Weight: 3.0, Số reviews toàn cục: 26.0)
      - Hạng 106: POI ID = 3815598 | Tên POI = Broma Not A Bar | (Total Weight: 3.0, Số reviews toàn cục: 21.0)
      - Hạng 151: POI ID = 6364047 | Tên POI = Lush | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
      - Hạng 283: POI ID = 9754920 | Tên POI = Snuffbox Speakeasy Cocktails Bar | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
      - Hạng 367: POI ID = 11872607 | Tên POI = ENVY Club | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
      - Hạng 687: POI ID = 25009311 | Tên POI = The Blinders Cocktail Bar | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
      - Hạng 614: POI ID = 18453788 | Tên POI = Krystalini Hidden Cocktail Bar | (Total Weight: 3.0, Số reviews toàn cục: 14.0)
      - Hạng 447: POI ID = 13225175 | Tên POI = The Iron Bank - Cocktail Vault | (Total Weight: 3.0, Số reviews toàn cục: 13.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 586 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1008 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1008
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 155: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 56: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 149: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 547: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 173: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 486: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 210: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 0 records POI có CÙNG DANH MỤC.
Tìm thấy 565 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
[Danh mục] Không tìm thấy record nào.
Gộp 3 danh sách (Outer Join): Tổng cộng có 988 records.

C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:121: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:122: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)

Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 988
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 157: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 151: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 537: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 477: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 41: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 211: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 69: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 42: POI ID = 1752815 | Tên POI = Saigon Saigon Rooftop Bar | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
Tìm thấy 101 records POI có CÙNG KHU VỰC.
Tìm thấy 15 records POI có CÙNG DANH MỤC.
Tìm thấy 24 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 101 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 15 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 118 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 118
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 32: POI ID = 11879452 | Tên POI = Hair Salon and Spa Angel Nguyen Thu | (Total Weight: 2.0, Số reviews toàn cục: 27.0)
      - Hạng 7: POI ID = 4177826 | Tên POI = Body Shape - Gym Thao Dien | (Total Weight: 2.0, Số reviews toàn cục: 17.0)
      - Hạng 46: POI ID = 14942510 | Tên POI = Mạ Non Spa | (Total Weight: 2.0, Số reviews toàn cục: 8.0)
      - Hạng 63: POI ID = 19102846 | Tên POI = Saigon Motorcycles | (Total Weight: 2.0, Số reviews toàn cục: 8.0)
      - Hạng 108: POI ID = 32983757 | Tên POI = Acuro Flight Simulator Center | (Total Weight: 2.0, Số reviews toàn cục: 6.0)
      - Hạng 27: POI ID = 11437239 | Tên POI = Green World Car Rental Company | (Total Weight: 2.0, Số reviews toàn cục: 5.0)
      - Hạng 87: POI ID = 26145540 | Tên POI = HAEU Salon | (Total Weight: 2.0, Số reviews toàn cục: 5.0)
      - Hạng 24: POI ID = 10801837 | Tên POI = Ngôi nhà Việt Nam | (Total Weight: 2.0, Số reviews toàn cục: 4.0)
      - Hạng 56: POI ID = 17558611 | Tên POI = Le Barbier de Saigon | (Total Weight: 2.0, Số reviews toàn cục: 4.0)
      - Hạng 75: POI ID = 24932763 | Tên POI = Homie Spa | (Total Weight: 2.0, Số reviews toàn cục: 4.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 386 records POI có CÙNG DANH MỤC.
Tìm thấy 449 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 386 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1048 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1048
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 715: POI ID = 23300698 | Tên POI = Euphorea Salon And Spa - Bason Branch | (Total Weight: 3.0, Số reviews toàn cục: 302.0)
      - Hạng 149: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 3.0, Số reviews toàn cục: 270.0)
      - Hạng 208: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 3.0, Số reviews toàn cục: 165.0)
      - Hạng 107: POI ID = 3749935 | Tên POI = Saigon Heritage Spa | (Total Weight: 3.0, Số reviews toàn cục: 128.0)
      - Hạng 441: POI ID = 12788024 | Tên POI = Ori Nail & Spa | (Total Weight: 3.0, Số reviews toàn cục: 86.0)
      - Hạng 682: POI ID = 19408793 | Tên POI = Mido  Spa | (Total Weight: 3.0, Số reviews toàn cục: 50.0)
      - Hạng 317: POI ID = 10455052 | Tên POI = Spa Gallery | (Total Weight: 3.0, Số reviews toàn cục: 49.0)
      - Hạng 61: POI ID = 2154294 | Tên POI = My Spa | (Total Weight: 3.0, Số reviews toàn cục: 48.0)
      - Hạng 795: POI ID = 26267736 | Tên POI = La Mekong Spa - Ngô Văn Năm | (Total Weight: 3.0, Số reviews toàn cục: 48.0)
      - Hạng 177: POI ID = 6864271 | Tên POI = Golden Lotus Spa & Massage Club | (Total Weight: 3.0, Số reviews toàn cục: 46.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 589 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1025 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1025
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 217: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 2.0, Số reviews toàn cục: 380.0)
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 161: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 152: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 560: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 180: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 498: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 482 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 561 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 561
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 2273343 | Tên POI = Phạm Ngũ Lão | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 118: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 24: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 177: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 401: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 144: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 312: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 81: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 482 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 561 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 561
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 2273343 | Tên POI = Phạm Ngũ Lão | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 118: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 24: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 177: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 401: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 144: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 312: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 81: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 12 records POI có CÙNG DANH MỤC.
Tìm thấy 605 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 12 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 698 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 698
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 162: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 38: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 244: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 518: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 110: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 9: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 415: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 112: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
      - Hạng 49: POI ID = 2273094 | Tên POI = Công Ty Tnhh Du Lịch Việt Vui | (Total Weight: 2.0, Số reviews toàn cục: 94.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 482 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 561 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 561
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 2273343 | Tên POI = Phạm Ngũ Lão | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 118: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 24: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 177: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 401: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 144: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 312: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 81: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 453 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 958 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 958
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 299: POI ID = 9974461 | Tên POI = Lăng Tả quân Lê Văn Duyệt | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 152: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 55: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 146: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 522: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 169: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 467: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 38: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 204: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 67: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 587 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1002 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1002
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 247: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 3.0, Số reviews toàn cục: 155.0)
      - Hạng 43: POI ID = 1784754 | Tên POI = Đường Đồng Khởi | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 890: POI ID = 32800829 | Tên POI = The Laundry + Rooftop Bar & Cafe | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 158: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 152: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 542: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 6: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 176: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 56: POI ID = 2005826 | Tên POI = Cu Chi Tunnels | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 0 records POI có CÙNG DANH MỤC.
Tìm thấy 587 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
[Danh mục] Không tìm thấy record nào.
Gộp 3 danh sách (Outer Join): Tổng cộng có 1001 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1001
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 157: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 151: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 541: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 6: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 175: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 480: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 41: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 212: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 69: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 386 records POI có CÙNG DANH MỤC.
Tìm thấy 375 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 386 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 695 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 695
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 75: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 3.0, Số reviews toàn cục: 101.0)
      - Hạng 222: POI ID = 11899009 | Tên POI = Coco Care Spa | (Total Weight: 3.0, Số reviews toàn cục: 47.0)
      - Hạng 33: POI ID = 2334935 | Tên POI = Foot Massage Salon Quỳnh Như 137 | (Total Weight: 3.0, Số reviews toàn cục: 45.0)
      - Hạng 180: POI ID = 10767864 | Tên POI = Rocky Spa | (Total Weight: 3.0, Số reviews toàn cục: 43.0)
      - Hạng 302: POI ID = 14116019 | Tên POI = Zen Spa - Foot & Body Massage | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 571: POI ID = 28029827 | Tên POI = Bông Spa (Branch Nguyen Canh Chan) | (Total Weight: 3.0, Số reviews toàn cục: 27.0)
      - Hạng 695: POI ID = 34495164 | Tên POI = NAP Healing & Wellness | (Total Weight: 3.0, Số reviews toàn cục: 25.0)
      - Hạng 52: POI ID = 2726268 | Tên POI = Cat Moc Spa | (Total Weight: 3.0, Số reviews toàn cục: 22.0)
      - Hạng 170: POI ID = 9974597 | Tên POI = Liberty Spa | (Total Weight: 3.0, Số reviews toàn cục: 19.0)
      - Hạng 106: POI ID = 6983488 | Tên POI = Kim Spa | (Total Weight: 3.0, Số reviews toàn cục: 14.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 482 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 561 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 561
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 2273343 | Tên POI = Phạm Ngũ Lão | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 118: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 24: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 177: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 401: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 144: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 312: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 81: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)

C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:121: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:122: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:127: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_nearby'] = recommended_interactions['weight_nearby'].fillna(0)

Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 0 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 825 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 825
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 207: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 9: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 2.0, Số reviews toàn cục: 126.0)
      - Hạng 7: POI ID = 317893 | Tên POI = Quảng trường Hồ Chí Minh | (Total Weight: 2.0, Số reviews toàn cục: 123.0)
      - Hạng 36: POI ID = 1784754 | Tên POI = Đường Đồng Khởi | (Total Weight: 2.0, Số reviews toàn cục: 41.0)
      - Hạng 113: POI ID = 4597843 | Tên POI = Binh Quoi Village | (Total Weight: 2.0, Số reviews toàn cục: 25.0)
      - Hạng 111: POI ID = 4559699 | Tên POI = Rung Sac Military Base | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 736: POI ID = 32800829 | Tên POI = The Laundry + Rooftop Bar & Cafe | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 205: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 1.0, Số reviews toàn cục: 1015.0)
      - Hạng 175: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 1.0, Số reviews toàn cục: 380.0)
      - Hạng 50: POI ID = 2044621 | Tên POI = XO Tours | (Total Weight: 1.0, Số reviews toàn cục: 360.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 10 records POI có CÙNG DANH MỤC.
Tìm thấy 626 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 10 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 734 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 734
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 164.0)
      - Hạng 318: POI ID = 12084531 | Tên POI = Chợ Đêm Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 46.0)
      - Hạng 75: POI ID = 2484797 | Tên POI = Dan Sinh Market | (Total Weight: 3.0, Số reviews toàn cục: 12.0)
      - Hạng 602: POI ID = 26899566 | Tên POI = Central Market 23.9 | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 173: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 43: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 541: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 222: POI ID = 8599407 | Tên POI = Saigon Adventure | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 117: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 7: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 2 records POI có CÙNG DANH MỤC.
Tìm thấy 613 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 2 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1018 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1018
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 212: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 2.0, Số reviews toàn cục: 380.0)
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 157: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 151: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 553: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 175: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 491: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 25 records POI có CÙNG DANH MỤC.
Tìm thấy 564 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 25 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 992 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 992
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 92: POI ID = 2475475 | Tên POI = Sai Gon Square | (Total Weight: 3.0, Số reviews toàn cục: 67.0)
      - Hạng 47: POI ID = 1830324 | Tên POI = Vincom Center | (Total Weight: 3.0, Số reviews toàn cục: 63.0)
      - Hạng 127: POI ID = 4552853 | Tên POI = Saigon Centre | (Total Weight: 3.0, Số reviews toàn cục: 42.0)
      - Hạng 237: POI ID = 8090785 | Tên POI = Chợ Nga | (Total Weight: 3.0, Số reviews toàn cục: 25.0)
      - Hạng 893: POI ID = 32983638 | Tên POI = Moji Shop 92 Ho Tung Mau | (Total Weight: 3.0, Số reviews toàn cục: 8.0)
      - Hạng 218: POI ID = 7743972 | Tên POI = Union Square | (Total Weight: 3.0, Số reviews toàn cục: 6.0)
      - Hạng 401: POI ID = 12125198 | Tên POI = Vòng Tròn Đỏ | (Total Weight: 3.0, Số reviews toàn cục: 6.0)
      - Hạng 970: POI ID = 34075184 | Tên POI = SARTOLAD Tailor - Bespoke & Suit | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 783: POI ID = 26790666 | Tên POI = Highway menswear | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 913: POI ID = 33131194 | Tên POI = Sai Gon Bookstore | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 494 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 959 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 959
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 146: POI ID = 5972878 | Tên POI = Dominique Saint Paul | (Total Weight: 3.0, Số reviews toàn cục: 5.0)
      - Hạng 151: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 55: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 145: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 520: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 464: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 203: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 67: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 638 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 725 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 725
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 169: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 39: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 248: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 536: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 217: POI ID = 8599407 | Tên POI = Saigon Adventure | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 113: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 425: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 115: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
      - Hạng 51: POI ID = 2273094 | Tên POI = Công Ty Tnhh Du Lịch Việt Vui | (Total Weight: 2.0, Số reviews toàn cục: 94.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 0 records POI có CÙNG DANH MỤC.
Tìm thấy 0 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
[Danh mục] Không tìm thấy record nào.
Gộp 3 danh sách (Outer Join): Tổng cộng có 823 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 823

C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:127: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_nearby'] = recommended_interactions['weight_nearby'].fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:127: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_nearby'] = recommended_interactions['weight_nearby'].fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:121: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:122: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)

*** Top 10 địa điểm được khuyến nghị:
      - Hạng 204: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 1, Số reviews toàn cục: 1015)
      - Hạng 174: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 1, Số reviews toàn cục: 380)
      - Hạng 51: POI ID = 2044621 | Tên POI = XO Tours | (Total Weight: 1, Số reviews toàn cục: 360)
      - Hạng 262: POI ID = 10044301 | Tên POI = Công ty cổ phần xe khách Phương Trang | (Total Weight: 1, Số reviews toàn cục: 318)
      - Hạng 119: POI ID = 4795476 | Tên POI = Phan's Custom Tailor | (Total Weight: 1, Số reviews toàn cục: 310)
      - Hạng 592: POI ID = 23300698 | Tên POI = Euphorea Salon And Spa - Bason Branch | (Total Weight: 1, Số reviews toàn cục: 302)
      - Hạng 31: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 1, Số reviews toàn cục: 294)
      - Hạng 133: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 1, Số reviews toàn cục: 294)
      - Hạng 50: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 1, Số reviews toàn cục: 287)
      - Hạng 128: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 1, Số reviews toàn cục: 270)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 0 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 825 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 825
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 48: POI ID = 2005826 | Tên POI = Cu Chi Tunnels | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 207: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 8: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 2.0, Số reviews toàn cục: 126.0)
      - Hạng 35: POI ID = 1784754 | Tên POI = Đường Đồng Khởi | (Total Weight: 2.0, Số reviews toàn cục: 41.0)
      - Hạng 113: POI ID = 4597843 | Tên POI = Binh Quoi Village | (Total Weight: 2.0, Số reviews toàn cục: 25.0)
      - Hạng 111: POI ID = 4559699 | Tên POI = Rung Sac Military Base | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 736: POI ID = 32800829 | Tên POI = The Laundry + Rooftop Bar & Cafe | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 205: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 1.0, Số reviews toàn cục: 1015.0)
      - Hạng 175: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 1.0, Số reviews toàn cục: 380.0)
      - Hạng 50: POI ID = 2044621 | Tên POI = XO Tours | (Total Weight: 1.0, Số reviews toàn cục: 360.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 453 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 958 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 958
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 299: POI ID = 9974461 | Tên POI = Lăng Tả quân Lê Văn Duyệt | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 152: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 55: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 146: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 522: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 169: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 467: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 38: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 204: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 67: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 386 records POI có CÙNG DANH MỤC.
Tìm thấy 479 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 386 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1066 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1066
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 151: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 3.0, Số reviews toàn cục: 270.0)
      - Hạng 210: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 3.0, Số reviews toàn cục: 165.0)
      - Hạng 109: POI ID = 3749935 | Tên POI = Saigon Heritage Spa | (Total Weight: 3.0, Số reviews toàn cục: 128.0)
      - Hạng 509: POI ID = 14025887 | Tên POI = The Privé Spa | International Lash, Nail Care & Spa | Ben Thanh (D1) | (Total Weight: 3.0, Số reviews toàn cục: 97.0)
      - Hạng 446: POI ID = 12788024 | Tên POI = Ori Nail & Spa | (Total Weight: 3.0, Số reviews toàn cục: 86.0)
      - Hạng 692: POI ID = 19408793 | Tên POI = Mido  Spa | (Total Weight: 3.0, Số reviews toàn cục: 50.0)
      - Hạng 321: POI ID = 10455052 | Tên POI = Spa Gallery | (Total Weight: 3.0, Số reviews toàn cục: 49.0)
      - Hạng 61: POI ID = 2154294 | Tên POI = My Spa | (Total Weight: 3.0, Số reviews toàn cục: 48.0)
      - Hạng 807: POI ID = 26267736 | Tên POI = La Mekong Spa - Ngô Văn Năm | (Total Weight: 3.0, Số reviews toàn cục: 48.0)
      - Hạng 179: POI ID = 6864271 | Tên POI = Golden Lotus Spa & Massage Club | (Total Weight: 3.0, Số reviews toàn cục: 46.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 0 records POI có CÙNG DANH MỤC.
Tìm thấy 584 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
[Danh mục] Không tìm thấy record nào.
Gộp 3 danh sách (Outer Join): Tổng cộng có 673 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 673
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 156: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 35: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 232: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 496: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 105: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 7: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 397: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 106: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
      - Hạng 45: POI ID = 2273094 | Tên POI = Công Ty Tnhh Du Lịch Việt Vui | (Total Weight: 2.0, Số reviews toàn cục: 94.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 482 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 561 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 561
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 2273343 | Tên POI = Phạm Ngũ Lão | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 118: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 24: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 177: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 401: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 144: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 312: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 81: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 587 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1002 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1002
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 247: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 3.0, Số reviews toàn cục: 155.0)
      - Hạng 43: POI ID = 1784754 | Tên POI = Đường Đồng Khởi | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 890: POI ID = 32800829 | Tên POI = The Laundry + Rooftop Bar & Cafe | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 158: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 152: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 542: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 6: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 176: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 56: POI ID = 2005826 | Tên POI = Cu Chi Tunnels | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 2 records POI có CÙNG DANH MỤC.
Tìm thấy 613 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 2 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1018 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1018
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 212: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 2.0, Số reviews toàn cục: 380.0)
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 157: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 151: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 553: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 175: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 491: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 4 records POI có CÙNG DANH MỤC.
Tìm thấy 1 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 4 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 824 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 824
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 331: POI ID = 12033619 | Tên POI = Rubik Zoo | (Total Weight: 2.0, Số reviews toàn cục: 11.0)
      - Hạng 32: POI ID = 1742604 | Tên POI = Dai Nam Zoo | (Total Weight: 2.0, Số reviews toàn cục: 6.0)
      - Hạng 482: POI ID = 16657089 | Tên POI = Công Viên Đầm Sen | (Total Weight: 2.0, Số reviews toàn cục: 2.0)
      - Hạng 804: POI ID = 33973175 | Tên POI = Kubet KYC | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 203: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 1.0, Số reviews toàn cục: 1015.0)
      - Hạng 173: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 1.0, Số reviews toàn cục: 380.0)
      - Hạng 50: POI ID = 2044621 | Tên POI = XO Tours | (Total Weight: 1.0, Số reviews toàn cục: 360.0)
      - Hạng 262: POI ID = 10044301 | Tên POI = Công ty cổ phần xe khách Phương Trang | (Total Weight: 1.0, Số reviews toàn cục: 318.0)
      - Hạng 118: POI ID = 4795476 | Tên POI = Phan's Custom Tailor | (Total Weight: 1.0, Số reviews toàn cục: 310.0)
      - Hạng 592: POI ID = 23300698 | Tên POI = Euphorea Salon And Spa - Bason Branch | (Total Weight: 1.0, Số reviews toàn cục: 302.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 0 records POI có CÙNG DANH MỤC.
Tìm thấy 587 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
[Danh mục] Không tìm thấy record nào.
Gộp 3 danh sách (Outer Join): Tổng cộng có 1001 records.

C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:121: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:122: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:121: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:122: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)

Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1001
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 157: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 151: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 541: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 6: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 175: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 480: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 41: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 212: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 69: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 531 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 992 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 992
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 11: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 3.0, Số reviews toàn cục: 126.0)
      - Hạng 42: POI ID = 1784754 | Tên POI = Đường Đồng Khởi | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 881: POI ID = 32800829 | Tên POI = The Laundry + Rooftop Bar & Cafe | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 155: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 149: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 538: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 173: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 12 records POI có CÙNG DANH MỤC.
Tìm thấy 190 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 12 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 454 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 454
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 113: POI ID = 8599407 | Tên POI = Saigon Adventure | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 340: POI ID = 25572460 | Tên POI = 1st Football Store Thach Thi Thanh | (Total Weight: 2.0, Số reviews toàn cục: 66.0)
      - Hạng 43: POI ID = 2487716 | Tên POI = Innoviet Travel | (Total Weight: 2.0, Số reviews toàn cục: 63.0)
      - Hạng 139: POI ID = 10085046 | Tên POI = Nhà thờ Tân Định | (Total Weight: 2.0, Số reviews toàn cục: 53.0)
      - Hạng 39: POI ID = 2435196 | Tên POI = Tiger Tours Co. Ltd. | (Total Weight: 2.0, Số reviews toàn cục: 38.0)
      - Hạng 36: POI ID = 2407915 | Tên POI = Mariamman Hindu Temple | (Total Weight: 2.0, Số reviews toàn cục: 36.0)
      - Hạng 361: POI ID = 27105186 | Tên POI = Wellness Center - Mint Gội Đầu Siêu Thư Giãn Quận 1 | (Total Weight: 2.0, Số reviews toàn cục: 34.0)
      - Hạng 83: POI ID = 7065652 | Tên POI = Bravo Indochina Tours | (Total Weight: 2.0, Số reviews toàn cục: 31.0)
      - Hạng 382: POI ID = 28010412 | Tên POI = Lam Spa | (Total Weight: 2.0, Số reviews toàn cục: 31.0)
      - Hạng 409: POI ID = 33007917 | Tên POI = Hum Spa Đặng Tất | (Total Weight: 2.0, Số reviews toàn cục: 28.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 10 records POI có CÙNG DANH MỤC.
Tìm thấy 606 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 10 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 700 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 700
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 242: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 3.0, Số reviews toàn cục: 246.0)
      - Hạng 302: POI ID = 12084531 | Tên POI = Chợ Đêm Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 46.0)
      - Hạng 68: POI ID = 2484797 | Tên POI = Dan Sinh Market | (Total Weight: 3.0, Số reviews toàn cục: 12.0)
      - Hạng 222: POI ID = 8827357 | Tên POI = Cho Thai Binh | (Total Weight: 3.0, Số reviews toàn cục: 5.0)
      - Hạng 574: POI ID = 26899566 | Tên POI = Central Market 23.9 | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 164: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 38: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 515: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 110: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 0 records POI có CÙNG DANH MỤC.
Tìm thấy 587 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
[Danh mục] Không tìm thấy record nào.
Gộp 3 danh sách (Outer Join): Tổng cộng có 1001 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1001
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 157: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 151: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 541: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 6: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 175: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 480: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 41: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 212: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 69: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 579 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 996 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 996
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 158: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 58: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 152: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 539: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 6: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 479: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 42: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 212: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 70: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 43: POI ID = 1752815 | Tên POI = Saigon Saigon Rooftop Bar | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 12 records POI có CÙNG DANH MỤC.
Tìm thấy 190 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 12 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 454 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 454
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 113: POI ID = 8599407 | Tên POI = Saigon Adventure | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 340: POI ID = 25572460 | Tên POI = 1st Football Store Thach Thi Thanh | (Total Weight: 2.0, Số reviews toàn cục: 66.0)
      - Hạng 43: POI ID = 2487716 | Tên POI = Innoviet Travel | (Total Weight: 2.0, Số reviews toàn cục: 63.0)
      - Hạng 139: POI ID = 10085046 | Tên POI = Nhà thờ Tân Định | (Total Weight: 2.0, Số reviews toàn cục: 53.0)
      - Hạng 39: POI ID = 2435196 | Tên POI = Tiger Tours Co. Ltd. | (Total Weight: 2.0, Số reviews toàn cục: 38.0)
      - Hạng 36: POI ID = 2407915 | Tên POI = Mariamman Hindu Temple | (Total Weight: 2.0, Số reviews toàn cục: 36.0)
      - Hạng 361: POI ID = 27105186 | Tên POI = Wellness Center - Mint Gội Đầu Siêu Thư Giãn Quận 1 | (Total Weight: 2.0, Số reviews toàn cục: 34.0)
      - Hạng 83: POI ID = 7065652 | Tên POI = Bravo Indochina Tours | (Total Weight: 2.0, Số reviews toàn cục: 31.0)
      - Hạng 382: POI ID = 28010412 | Tên POI = Lam Spa | (Total Weight: 2.0, Số reviews toàn cục: 31.0)
      - Hạng 409: POI ID = 33007917 | Tên POI = Hum Spa Đặng Tất | (Total Weight: 2.0, Số reviews toàn cục: 28.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 4 records POI có CÙNG DANH MỤC.
Tìm thấy 536 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 4 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 980 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 980
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 122: POI ID = 4542125 | Tên POI = À Ố Show - Lune Production | (Total Weight: 3.0, Số reviews toàn cục: 59.0)
      - Hạng 343: POI ID = 11443657 | Tên POI = Nhà Hát Giao Hưởng Nhạc Vũ kịch Thành Phố Hồ Chí Minh | (Total Weight: 3.0, Số reviews toàn cục: 4.0)
      - Hạng 154: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 56: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 148: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 532: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 172: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 475: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 39: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 25 records POI có CÙNG DANH MỤC.
Tìm thấy 588 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 25 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1036 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1036
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 46: POI ID = 1830324 | Tên POI = Vincom Center | (Total Weight: 3.0, Số reviews toàn cục: 63.0)
      - Hạng 126: POI ID = 4552853 | Tên POI = Saigon Centre | (Total Weight: 3.0, Số reviews toàn cục: 42.0)
      - Hạng 19: POI ID = 550709 | Tên POI = Diamond Plaza | (Total Weight: 3.0, Số reviews toàn cục: 25.0)
      - Hạng 246: POI ID = 8090785 | Tên POI = Chợ Nga | (Total Weight: 3.0, Số reviews toàn cục: 25.0)
      - Hạng 932: POI ID = 32983638 | Tên POI = Moji Shop 92 Ho Tung Mau | (Total Weight: 3.0, Số reviews toàn cục: 8.0)
      - Hạng 227: POI ID = 7743972 | Tên POI = Union Square | (Total Weight: 3.0, Số reviews toàn cục: 6.0)
      - Hạng 419: POI ID = 12125198 | Tên POI = Vòng Tròn Đỏ | (Total Weight: 3.0, Số reviews toàn cục: 6.0)
      - Hạng 822: POI ID = 26790666 | Tên POI = Highway menswear | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 953: POI ID = 33131194 | Tên POI = Sai Gon Bookstore | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 218: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 2.0, Số reviews toàn cục: 380.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 638 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 725 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 725
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 169: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 39: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 248: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 536: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 217: POI ID = 8599407 | Tên POI = Saigon Adventure | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 113: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 425: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 115: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
      - Hạng 51: POI ID = 2273094 | Tên POI = Công Ty Tnhh Du Lịch Việt Vui | (Total Weight: 2.0, Số reviews toàn cục: 94.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 510 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 995 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 995
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 705: POI ID = 21230453 | Tên POI = Saigon Skydeck | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 155: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 149: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 540: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 173: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 481: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 208: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 68: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 482 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 561 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 561
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 2273343 | Tên POI = Phạm Ngũ Lão | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 118: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 24: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 177: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 401: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 144: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 312: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 81: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 10 records POI có CÙNG DANH MỤC.
Tìm thấy 626 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 10 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 734 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 734
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 164.0)
      - Hạng 318: POI ID = 12084531 | Tên POI = Chợ Đêm Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 46.0)
      - Hạng 75: POI ID = 2484797 | Tên POI = Dan Sinh Market | (Total Weight: 3.0, Số reviews toàn cục: 12.0)
      - Hạng 602: POI ID = 26899566 | Tên POI = Central Market 23.9 | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 173: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 43: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 541: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 222: POI ID = 8599407 | Tên POI = Saigon Adventure | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 117: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 7: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)

C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:127: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_nearby'] = recommended_interactions['weight_nearby'].fillna(0)

Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 823
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 204: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 1, Số reviews toàn cục: 1015)
      - Hạng 174: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 1, Số reviews toàn cục: 380)
      - Hạng 51: POI ID = 2044621 | Tên POI = XO Tours | (Total Weight: 1, Số reviews toàn cục: 360)
      - Hạng 262: POI ID = 10044301 | Tên POI = Công ty cổ phần xe khách Phương Trang | (Total Weight: 1, Số reviews toàn cục: 318)
      - Hạng 119: POI ID = 4795476 | Tên POI = Phan's Custom Tailor | (Total Weight: 1, Số reviews toàn cục: 310)
      - Hạng 592: POI ID = 23300698 | Tên POI = Euphorea Salon And Spa - Bason Branch | (Total Weight: 1, Số reviews toàn cục: 302)
      - Hạng 31: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 1, Số reviews toàn cục: 294)
      - Hạng 133: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 1, Số reviews toàn cục: 294)
      - Hạng 50: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 1, Số reviews toàn cục: 287)
      - Hạng 128: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 1, Số reviews toàn cục: 270)
Tìm thấy 9 records POI có CÙNG KHU VỰC.
Tìm thấy 5 records POI có CÙNG DANH MỤC.
Tìm thấy 195 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 9 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 5 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 206 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 206
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 53: POI ID = 8532676 | Tên POI = Sơn Mài Việt Nam | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 109: POI ID = 17432329 | Tên POI = The Beauty House & Academy | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 51: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 1.0, Số reviews toàn cục: 1015.0)
      - Hạng 63: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 1.0, Số reviews toàn cục: 246.0)
      - Hạng 55: POI ID = 8599407 | Tên POI = Saigon Adventure | (Total Weight: 1.0, Số reviews toàn cục: 176.0)
      - Hạng 34: POI ID = 3948543 | Tên POI = Saigon Hotpot - Travel With Local Youth | (Total Weight: 1.0, Số reviews toàn cục: 144.0)
      - Hạng 1: POI ID = 311089 | Tên POI = Bưu điện trung tâm Sài Gòn | (Total Weight: 1.0, Số reviews toàn cục: 139.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 1.0, Số reviews toàn cục: 138.0)
      - Hạng 8: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 1.0, Số reviews toàn cục: 126.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 12 records POI có CÙNG DANH MỤC.
Tìm thấy 182 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 12 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 879 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 879
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 76: POI ID = 2385857 | Tên POI = Chua Vinh Nghiem | (Total Weight: 3.0, Số reviews toàn cục: 20.0)
      - Hạng 21: POI ID = 552637 | Tên POI = Temple of the Buddha's Relic (Xa Loi pagoda) | (Total Weight: 3.0, Số reviews toàn cục: 17.0)
      - Hạng 219: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 2.0, Số reviews toàn cục: 1015.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 106: POI ID = 3948543 | Tên POI = Saigon Hotpot - Travel With Local Youth | (Total Weight: 2.0, Số reviews toàn cục: 144.0)
      - Hạng 1: POI ID = 311089 | Tên POI = Bưu điện trung tâm Sài Gòn | (Total Weight: 2.0, Số reviews toàn cục: 139.0)
      - Hạng 11: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 2.0, Số reviews toàn cục: 126.0)
      - Hạng 10: POI ID = 317896 | Tên POI = Nhà thờ Đức Bà Sài Gòn | (Total Weight: 2.0, Số reviews toàn cục: 118.0)
      - Hạng 299: POI ID = 10836601 | Tên POI = Đường Sách Nguyễn Văn Bình | (Total Weight: 2.0, Số reviews toàn cục: 113.0)
      - Hạng 531: POI ID = 17379413 | Tên POI = Heritage Line - Refined Waterway Voyages | (Total Weight: 2.0, Số reviews toàn cục: 106.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 25 records POI có CÙNG DANH MỤC.
Tìm thấy 574 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 25 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1007 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1007
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 90: POI ID = 2475475 | Tên POI = Sai Gon Square | (Total Weight: 3.0, Số reviews toàn cục: 67.0)
      - Hạng 46: POI ID = 1830324 | Tên POI = Vincom Center | (Total Weight: 3.0, Số reviews toàn cục: 63.0)
      - Hạng 125: POI ID = 4552853 | Tên POI = Saigon Centre | (Total Weight: 3.0, Số reviews toàn cục: 42.0)
      - Hạng 19: POI ID = 550709 | Tên POI = Diamond Plaza | (Total Weight: 3.0, Số reviews toàn cục: 25.0)
      - Hạng 237: POI ID = 8090785 | Tên POI = Chợ Nga | (Total Weight: 3.0, Số reviews toàn cục: 25.0)
      - Hạng 905: POI ID = 32983638 | Tên POI = Moji Shop 92 Ho Tung Mau | (Total Weight: 3.0, Số reviews toàn cục: 8.0)
      - Hạng 407: POI ID = 12125198 | Tên POI = Vòng Tròn Đỏ | (Total Weight: 3.0, Số reviews toàn cục: 6.0)
      - Hạng 985: POI ID = 34075184 | Tên POI = SARTOLAD Tailor - Bespoke & Suit | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 799: POI ID = 26790666 | Tên POI = Highway menswear | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 926: POI ID = 33131194 | Tên POI = Sai Gon Bookstore | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 12 records POI có CÙNG DANH MỤC.
Tìm thấy 26 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 12 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 825 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 825
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 65: POI ID = 2273335 | Tên POI = Chùa Bà Thiên Hậu | (Total Weight: 3.0, Số reviews toàn cục: 69.0)
      - Hạng 243: POI ID = 8856733 | Tên POI = Hội quán Phước An | (Total Weight: 3.0, Số reviews toàn cục: 5.0)
      - Hạng 6: POI ID = 311105 | Tên POI = Chùa Ông Bổn | (Total Weight: 3.0, Số reviews toàn cục: 2.0)
      - Hạng 264: POI ID = 10044301 | Tên POI = Công ty cổ phần xe khách Phương Trang | (Total Weight: 2.0, Số reviews toàn cục: 318.0)
      - Hạng 244: POI ID = 8869748 | Tên POI = Vinasun Taxi | (Total Weight: 2.0, Số reviews toàn cục: 79.0)
      - Hạng 267: POI ID = 10085046 | Tên POI = Nhà thờ Tân Định | (Total Weight: 2.0, Số reviews toàn cục: 53.0)
      - Hạng 667: POI ID = 27130109 | Tên POI = Master Escape | (Total Weight: 2.0, Số reviews toàn cục: 40.0)
      - Hạng 415: POI ID = 13957334 | Tên POI = Vietnam Silver House | (Total Weight: 2.0, Số reviews toàn cục: 35.0)
      - Hạng 414: POI ID = 13934245 | Tên POI = Mon Amie Tailor - Best Tailor in HCMC | (Total Weight: 2.0, Số reviews toàn cục: 30.0)
      - Hạng 12: POI ID = 454972 | Tên POI = Phố Tàu Sài Gòn (Chợ Lớn Quận 5) | (Total Weight: 2.0, Số reviews toàn cục: 28.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 548 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 626 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 626
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 94: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 3.0, Số reviews toàn cục: 160.0)
      - Hạng 139: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 31: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 207: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 454: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 169: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 7: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 10: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 2.0, Số reviews toàn cục: 126.0)
      - Hạng 360: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 12 records POI có CÙNG DANH MỤC.
Tìm thấy 22 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 12 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 825 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 825
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 242: POI ID = 8856733 | Tên POI = Hội quán Phước An | (Total Weight: 3.0, Số reviews toàn cục: 5.0)
      - Hạng 257: POI ID = 9806515 | Tên POI = Chùa Nghĩa An | (Total Weight: 3.0, Số reviews toàn cục: 4.0)
      - Hạng 6: POI ID = 311105 | Tên POI = Chùa Ông Bổn | (Total Weight: 3.0, Số reviews toàn cục: 2.0)
      - Hạng 264: POI ID = 10044301 | Tên POI = Công ty cổ phần xe khách Phương Trang | (Total Weight: 2.0, Số reviews toàn cục: 318.0)
      - Hạng 243: POI ID = 8869748 | Tên POI = Vinasun Taxi | (Total Weight: 2.0, Số reviews toàn cục: 79.0)
      - Hạng 267: POI ID = 10085046 | Tên POI = Nhà thờ Tân Định | (Total Weight: 2.0, Số reviews toàn cục: 53.0)
      - Hạng 12: POI ID = 454972 | Tên POI = Phố Tàu Sài Gòn (Chợ Lớn Quận 5) | (Total Weight: 2.0, Số reviews toàn cục: 28.0)
      - Hạng 21: POI ID = 635380 | Tên POI = Bình Tây Market | (Total Weight: 2.0, Số reviews toàn cục: 27.0)
      - Hạng 70: POI ID = 2385857 | Tên POI = Chua Vinh Nghiem | (Total Weight: 2.0, Số reviews toàn cục: 20.0)
      - Hạng 7: POI ID = 317889 | Tên POI = Giac Lam Pagoda | (Total Weight: 2.0, Số reviews toàn cục: 18.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 25 records POI có CÙNG DANH MỤC.
Tìm thấy 588 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 25 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1036 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1036
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 46: POI ID = 1830324 | Tên POI = Vincom Center | (Total Weight: 3.0, Số reviews toàn cục: 63.0)
      - Hạng 126: POI ID = 4552853 | Tên POI = Saigon Centre | (Total Weight: 3.0, Số reviews toàn cục: 42.0)
      - Hạng 19: POI ID = 550709 | Tên POI = Diamond Plaza | (Total Weight: 3.0, Số reviews toàn cục: 25.0)
      - Hạng 246: POI ID = 8090785 | Tên POI = Chợ Nga | (Total Weight: 3.0, Số reviews toàn cục: 25.0)
      - Hạng 932: POI ID = 32983638 | Tên POI = Moji Shop 92 Ho Tung Mau | (Total Weight: 3.0, Số reviews toàn cục: 8.0)
      - Hạng 227: POI ID = 7743972 | Tên POI = Union Square | (Total Weight: 3.0, Số reviews toàn cục: 6.0)
      - Hạng 419: POI ID = 12125198 | Tên POI = Vòng Tròn Đỏ | (Total Weight: 3.0, Số reviews toàn cục: 6.0)
      - Hạng 822: POI ID = 26790666 | Tên POI = Highway menswear | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 953: POI ID = 33131194 | Tên POI = Sai Gon Bookstore | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 218: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 2.0, Số reviews toàn cục: 380.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 482 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 561 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 561
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 2273343 | Tên POI = Phạm Ngũ Lão | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 118: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 24: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 177: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 401: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 144: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 312: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 81: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 638 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 725 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 725
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 169: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 39: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 248: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 536: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 217: POI ID = 8599407 | Tên POI = Saigon Adventure | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 113: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 425: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
      - Hạng 115: POI ID = 5921457 | Tên POI = Beautiful Saigon Spa | (Total Weight: 2.0, Số reviews toàn cục: 101.0)
      - Hạng 51: POI ID = 2273094 | Tên POI = Công Ty Tnhh Du Lịch Việt Vui | (Total Weight: 2.0, Số reviews toàn cục: 94.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 25 records POI có CÙNG DANH MỤC.
Tìm thấy 564 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 25 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 992 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 992
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 92: POI ID = 2475475 | Tên POI = Sai Gon Square | (Total Weight: 3.0, Số reviews toàn cục: 67.0)
      - Hạng 47: POI ID = 1830324 | Tên POI = Vincom Center | (Total Weight: 3.0, Số reviews toàn cục: 63.0)
      - Hạng 127: POI ID = 4552853 | Tên POI = Saigon Centre | (Total Weight: 3.0, Số reviews toàn cục: 42.0)
      - Hạng 237: POI ID = 8090785 | Tên POI = Chợ Nga | (Total Weight: 3.0, Số reviews toàn cục: 25.0)
      - Hạng 893: POI ID = 32983638 | Tên POI = Moji Shop 92 Ho Tung Mau | (Total Weight: 3.0, Số reviews toàn cục: 8.0)
      - Hạng 218: POI ID = 7743972 | Tên POI = Union Square | (Total Weight: 3.0, Số reviews toàn cục: 6.0)
      - Hạng 401: POI ID = 12125198 | Tên POI = Vòng Tròn Đỏ | (Total Weight: 3.0, Số reviews toàn cục: 6.0)
      - Hạng 970: POI ID = 34075184 | Tên POI = SARTOLAD Tailor - Bespoke & Suit | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 783: POI ID = 26790666 | Tên POI = Highway menswear | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 913: POI ID = 33131194 | Tên POI = Sai Gon Bookstore | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 10 records POI có CÙNG DANH MỤC.
Tìm thấy 626 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 10 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 734 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 734
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 164.0)
      - Hạng 318: POI ID = 12084531 | Tên POI = Chợ Đêm Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 46.0)
      - Hạng 75: POI ID = 2484797 | Tên POI = Dan Sinh Market | (Total Weight: 3.0, Số reviews toàn cục: 12.0)
      - Hạng 602: POI ID = 26899566 | Tên POI = Central Market 23.9 | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 173: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 43: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 541: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 222: POI ID = 8599407 | Tên POI = Saigon Adventure | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 117: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 7: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 586 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1008 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1008
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 155: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 56: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 149: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 547: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 173: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 486: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 210: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 453 records POI LÂN CẬN (< 1.5km).

C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:121: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:122: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:121: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:122: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)

Tìm thấy 386 records POI có CÙNG DANH MỤC.
Tìm thấy 545 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 386 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1124 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1124
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 157: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 3.0, Số reviews toàn cục: 270.0)
      - Hạng 113: POI ID = 3749935 | Tên POI = Saigon Heritage Spa | (Total Weight: 3.0, Số reviews toàn cục: 128.0)
      - Hạng 482: POI ID = 12788024 | Tên POI = Ori Nail & Spa | (Total Weight: 3.0, Số reviews toàn cục: 86.0)
      - Hạng 742: POI ID = 19408793 | Tên POI = Mido  Spa | (Total Weight: 3.0, Số reviews toàn cục: 50.0)
      - Hạng 736: POI ID = 19259802 | Tên POI = Fame Nails | (Total Weight: 3.0, Số reviews toàn cục: 43.0)
      - Hạng 649: POI ID = 16835208 | Tên POI = The Blush Spa | (Total Weight: 3.0, Số reviews toàn cục: 37.0)
      - Hạng 154: POI ID = 5957860 | Tên POI = Golden Lotus Healing Land | (Total Weight: 3.0, Số reviews toàn cục: 36.0)
      - Hạng 805: POI ID = 25006681 | Tên POI = Hazgen Nail Bar | (Total Weight: 3.0, Số reviews toàn cục: 36.0)
      - Hạng 893: POI ID = 26923954 | Tên POI = Mint - Super Relaxing Massage | (Total Weight: 3.0, Số reviews toàn cục: 27.0)
      - Hạng 281: POI ID = 8602484 | Tên POI = May Spa | (Total Weight: 3.0, Số reviews toàn cục: 26.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 531 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 992 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 992
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 11: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 3.0, Số reviews toàn cục: 126.0)
      - Hạng 42: POI ID = 1784754 | Tên POI = Đường Đồng Khởi | (Total Weight: 3.0, Số reviews toàn cục: 41.0)
      - Hạng 881: POI ID = 32800829 | Tên POI = The Laundry + Rooftop Bar & Cafe | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 155: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 57: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 149: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 538: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 173: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 10 records POI có CÙNG DANH MỤC.
Tìm thấy 606 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 10 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 700 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 700
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 242: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 3.0, Số reviews toàn cục: 246.0)
      - Hạng 302: POI ID = 12084531 | Tên POI = Chợ Đêm Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 46.0)
      - Hạng 68: POI ID = 2484797 | Tên POI = Dan Sinh Market | (Total Weight: 3.0, Số reviews toàn cục: 12.0)
      - Hạng 222: POI ID = 8827357 | Tên POI = Cho Thai Binh | (Total Weight: 3.0, Số reviews toàn cục: 5.0)
      - Hạng 574: POI ID = 26899566 | Tên POI = Central Market 23.9 | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 164: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 38: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 515: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 110: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 6: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 0 records POI có CÙNG DANH MỤC.
Tìm thấy 528 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
[Danh mục] Không tìm thấy record nào.
Gộp 3 danh sách (Outer Join): Tổng cộng có 977 records.

C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:121: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:122: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:127: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_nearby'] = recommended_interactions['weight_nearby'].fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['user_id'] = recommended_interactions['user_id_region'].fillna(recommended_interactions['user_id_category']).fillna(recommended_interactions['user_id_nearby']).fillna(user_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:121: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['poi_id'] = recommended_interactions['poi_id_region'].fillna(recommended_interactions['poi_id_category']).fillna(recommended_interactions['poi_id_nearby']).fillna(poi_id)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:122: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['occurrences'] = recommended_interactions['occurrences_region'].fillna(recommended_interactions['occurrences_category']).fillna(recommended_interactions['occurrences_nearby']).fillna(0)
C:\Users\admin\AppData\Local\Temp\ipykernel_20984\1452251210.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  recommended_interactions['weight_category'] = recommended_interactions['weight_category'].fillna(0)

Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 977
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 154: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 56: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 148: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 531: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 172: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 474: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 208: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
      - Hạng 68: POI ID = 2264651 | Tên POI = Back of the Bike Tours | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
Tìm thấy 101 records POI có CÙNG KHU VỰC.
Tìm thấy 386 records POI có CÙNG DANH MỤC.
Tìm thấy 39 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 101 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 386 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 461 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 461
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 114: POI ID = 11746398 | Tên POI = Golden Lotus Healing World | (Total Weight: 3.0, Số reviews toàn cục: 275.0)
      - Hạng 15: POI ID = 2414201 | Tên POI = Concept Coiffure | (Total Weight: 3.0, Số reviews toàn cục: 21.0)
      - Hạng 385: POI ID = 29037205 | Tên POI = Hair Salon • Nail • Spa - Padaha | (Total Weight: 3.0, Số reviews toàn cục: 11.0)
      - Hạng 184: POI ID = 14942510 | Tên POI = Mạ Non Spa | (Total Weight: 3.0, Số reviews toàn cục: 8.0)
      - Hạng 62: POI ID = 7915234 | Tên POI = Quynh Salon | (Total Weight: 3.0, Số reviews toàn cục: 4.0)
      - Hạng 273: POI ID = 24932763 | Tên POI = Homie Spa | (Total Weight: 3.0, Số reviews toàn cục: 4.0)
      - Hạng 378: POI ID = 28660919 | Tên POI = Therésa Spa | (Total Weight: 3.0, Số reviews toàn cục: 4.0)
      - Hạng 128: POI ID = 12374411 | Tên POI = Lá Sen Spa | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 213: POI ID = 16855050 | Tên POI = Moc Huong Spa Gallery | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 348: POI ID = 27648721 | Tên POI = Waxing Hoa Hồ Chí Minh | (Total Weight: 3.0, Số reviews toàn cục: 2.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 586 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1008 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1008
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 155: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 56: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 149: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 547: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 173: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 486: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 210: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 548 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 626 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 626
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 94: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 3.0, Số reviews toàn cục: 160.0)
      - Hạng 139: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 31: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 207: POI ID = 10005057 | Tên POI = Ben Nghe Street Food | (Total Weight: 2.0, Số reviews toàn cục: 246.0)
      - Hạng 454: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 2.0, Số reviews toàn cục: 164.0)
      - Hạng 169: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 7: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
      - Hạng 10: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 2.0, Số reviews toàn cục: 126.0)
      - Hạng 360: POI ID = 15528737 | Tên POI = HANA TOURIST VIP | (Total Weight: 2.0, Số reviews toàn cục: 109.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 0 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 825 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 825
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 207: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 2.0, Số reviews toàn cục: 155.0)
      - Hạng 9: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 2.0, Số reviews toàn cục: 126.0)
      - Hạng 7: POI ID = 317893 | Tên POI = Quảng trường Hồ Chí Minh | (Total Weight: 2.0, Số reviews toàn cục: 123.0)
      - Hạng 36: POI ID = 1784754 | Tên POI = Đường Đồng Khởi | (Total Weight: 2.0, Số reviews toàn cục: 41.0)
      - Hạng 113: POI ID = 4597843 | Tên POI = Binh Quoi Village | (Total Weight: 2.0, Số reviews toàn cục: 25.0)
      - Hạng 111: POI ID = 4559699 | Tên POI = Rung Sac Military Base | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 736: POI ID = 32800829 | Tên POI = The Laundry + Rooftop Bar & Cafe | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 205: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 1.0, Số reviews toàn cục: 1015.0)
      - Hạng 175: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 1.0, Số reviews toàn cục: 380.0)
      - Hạng 50: POI ID = 2044621 | Tên POI = XO Tours | (Total Weight: 1.0, Số reviews toàn cục: 360.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 0 records POI có CÙNG DANH MỤC.
Tìm thấy 19 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
[Danh mục] Không tìm thấy record nào.
Gộp 3 danh sách (Outer Join): Tổng cộng có 833 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 833
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 230: POI ID = 8754863 | Tên POI = Trung Tâm Thương Mại Cresent Mall | (Total Weight: 2.0, Số reviews toàn cục: 18.0)
      - Hạng 258: POI ID = 9882201 | Tên POI = Anna Sanctuary Wellness Spa | (Total Weight: 2.0, Số reviews toàn cục: 8.0)
      - Hạng 117: POI ID = 4773063 | Tên POI = Body by Jovie | (Total Weight: 2.0, Số reviews toàn cục: 7.0)
      - Hạng 208: POI ID = 8295665 | Tên POI = Trung Tâm Hội Chợ Và Triển Lãm Sài Gòn - Secc | (Total Weight: 2.0, Số reviews toàn cục: 7.0)
      - Hạng 201: POI ID = 8181417 | Tên POI = Chợ Tân Mỹ | (Total Weight: 2.0, Số reviews toàn cục: 5.0)
      - Hạng 316: POI ID = 11741470 | Tên POI = Massage Người Khiếm Thị Ánh Dương 2 | (Total Weight: 2.0, Số reviews toàn cục: 3.0)
      - Hạng 807: POI ID = 33712421 | Tên POI = Oriental Retreat Spa & Wellness | (Total Weight: 2.0, Số reviews toàn cục: 2.0)
      - Hạng 553: POI ID = 18978667 | Tên POI = Halulu Nail | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 799: POI ID = 33358764 | Tên POI = Hey Jack Spa | (Total Weight: 2.0, Số reviews toàn cục: 1.0)
      - Hạng 204: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 1.0, Số reviews toàn cục: 1015.0)
Tìm thấy 101 records POI có CÙNG KHU VỰC.
Tìm thấy 2 records POI có CÙNG DANH MỤC.
Tìm thấy 67 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 101 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 2 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 111 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 111
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 31: POI ID = 11746398 | Tên POI = Golden Lotus Healing World | (Total Weight: 2.0, Số reviews toàn cục: 275.0)
      - Hạng 92: POI ID = 27705549 | Tên POI = Léa Beauty | (Total Weight: 2.0, Số reviews toàn cục: 48.0)
      - Hạng 54: POI ID = 17838697 | Tên POI = In The Mood - Saïgon | (Total Weight: 2.0, Số reviews toàn cục: 37.0)
      - Hạng 19: POI ID = 8556994 | Tên POI = amaï | (Total Weight: 2.0, Số reviews toàn cục: 30.0)
      - Hạng 32: POI ID = 11879452 | Tên POI = Hair Salon and Spa Angel Nguyen Thu | (Total Weight: 2.0, Số reviews toàn cục: 27.0)
      - Hạng 3: POI ID = 2414201 | Tên POI = Concept Coiffure | (Total Weight: 2.0, Số reviews toàn cục: 21.0)
      - Hạng 8: POI ID = 4826315 | Tên POI = Villa Royale Antiques and Tea Room | (Total Weight: 2.0, Số reviews toàn cục: 18.0)
      - Hạng 7: POI ID = 4177826 | Tên POI = Body Shape - Gym Thao Dien | (Total Weight: 2.0, Số reviews toàn cục: 17.0)
      - Hạng 30: POI ID = 11690404 | Tên POI = Mộc Hương Spa - Thảo Điền | (Total Weight: 2.0, Số reviews toàn cục: 14.0)
      - Hạng 48: POI ID = 16913859 | Tên POI = Laiday Refill | (Total Weight: 2.0, Số reviews toàn cục: 12.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 1 records POI có CÙNG DANH MỤC.
Tìm thấy 586 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 1 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1008 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1008
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 155: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 56: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 149: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 547: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 173: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 486: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 210: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 9 records POI có CÙNG DANH MỤC.
Tìm thấy 532 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 9 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 979 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 979
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 240: POI ID = 8290115 | Tên POI = Phố đi bộ Nguyễn Huệ | (Total Weight: 3.0, Số reviews toàn cục: 155.0)
      - Hạng 11: POI ID = 317898 | Tên POI = Notre Dame Square | (Total Weight: 3.0, Số reviews toàn cục: 126.0)
      - Hạng 870: POI ID = 32800829 | Tên POI = The Laundry + Rooftop Bar & Cafe | (Total Weight: 3.0, Số reviews toàn cục: 1.0)
      - Hạng 35: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 154: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 56: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 148: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 531: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 172: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 7 records POI có CÙNG DANH MỤC.
Tìm thấy 455 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 7 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 1048 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 1048
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 3: POI ID = 311092 | Tên POI = Cong Vien Van Hoa Park | (Total Weight: 3.0, Số reviews toàn cục: 21.0)
      - Hạng 82: POI ID = 2357145 | Tên POI = Cong Vien 23 Thang 9 | (Total Weight: 3.0, Số reviews toàn cục: 15.0)
      - Hạng 255: POI ID = 8263413 | Tên POI = Deluxe Group Tours | (Total Weight: 2.0, Số reviews toàn cục: 1015.0)
      - Hạng 221: POI ID = 7333808 | Tên POI = Vietnam Travel Group | (Total Weight: 2.0, Số reviews toàn cục: 380.0)
      - Hạng 36: POI ID = 1557134 | Tên POI = TNK Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 575: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 184: POI ID = 6721127 | Tên POI = Kim Travel | (Total Weight: 2.0, Số reviews toàn cục: 205.0)
      - Hạng 114: POI ID = 3948543 | Tên POI = Saigon Hotpot - Travel With Local Youth | (Total Weight: 2.0, Số reviews toàn cục: 144.0)
      - Hạng 2: POI ID = 311089 | Tên POI = Bưu điện trung tâm Sài Gòn | (Total Weight: 2.0, Số reviews toàn cục: 139.0)
Tìm thấy 299 records POI có CÙNG KHU VỰC.
Tìm thấy 10 records POI có CÙNG DANH MỤC.
Tìm thấy 626 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 299 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 10 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 734 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 734
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 1: POI ID = 311087 | Tên POI = Chợ Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 164.0)
      - Hạng 318: POI ID = 12084531 | Tên POI = Chợ Đêm Bến Thành | (Total Weight: 3.0, Số reviews toàn cục: 46.0)
      - Hạng 75: POI ID = 2484797 | Tên POI = Dan Sinh Market | (Total Weight: 3.0, Số reviews toàn cục: 12.0)
      - Hạng 602: POI ID = 26899566 | Tên POI = Central Market 23.9 | (Total Weight: 3.0, Số reviews toàn cục: 3.0)
      - Hạng 173: POI ID = 7171779 | Tên POI = Vietnam Adventure Tours | (Total Weight: 2.0, Số reviews toàn cục: 1110.0)
      - Hạng 43: POI ID = 2004786 | Tên POI = Vespa Adventures | (Total Weight: 2.0, Số reviews toàn cục: 387.0)
      - Hạng 541: POI ID = 24162332 | Tên POI = Monkee Shisha Lounge Saigon | (Total Weight: 2.0, Số reviews toàn cục: 204.0)
      - Hạng 222: POI ID = 8599407 | Tên POI = Saigon Adventure | (Total Weight: 2.0, Số reviews toàn cục: 176.0)
      - Hạng 117: POI ID = 5505885 | Tên POI = Đường Bùi Viện | (Total Weight: 2.0, Số reviews toàn cục: 160.0)
      - Hạng 7: POI ID = 317890 | Tên POI = Dinh Độc Lập | (Total Weight: 2.0, Số reviews toàn cục: 138.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 6 records POI có CÙNG DANH MỤC.
Tìm thấy 9 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 6 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 827 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 827
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 263: POI ID = 10044301 | Tên POI = Công ty cổ phần xe khách Phương Trang | (Total Weight: 2.0, Số reviews toàn cục: 318.0)
      - Hạng 453: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 466: POI ID = 15300685 | Tên POI = Kumho Samco Buslines | (Total Weight: 2.0, Số reviews toàn cục: 73.0)
      - Hạng 356: POI ID = 12511664 | Tên POI = Thành Bưởi | (Total Weight: 2.0, Số reviews toàn cục: 21.0)
      - Hạng 577: POI ID = 19492961 | Tên POI = Coffee Talk English - CTE | (Total Weight: 2.0, Số reviews toàn cục: 17.0)
      - Hạng 476: POI ID = 15661497 | Tên POI = 3S Limo | (Total Weight: 2.0, Số reviews toàn cục: 12.0)
      - Hạng 253: POI ID = 9806390 | Tên POI = Bến xe Chợ Lớn | (Total Weight: 2.0, Số reviews toàn cục: 7.0)
      - Hạng 165: POI ID = 7057020 | Tên POI = Nadam Spa | (Total Weight: 2.0, Số reviews toàn cục: 5.0)
      - Hạng 656: POI ID = 26866574 | Tên POI = Bình Thạnh Massage Foot Body & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 3.0)
      - Hạng 813: POI ID = 34081808 | Tên POI = Whale Hair Salon Vietnam | (Total Weight: 2.0, Số reviews toàn cục: 2.0)
Tìm thấy 823 records POI có CÙNG KHU VỰC.
Tìm thấy 2 records POI có CÙNG DANH MỤC.
Tìm thấy 535 records POI LÂN CẬN (< 1.5km).
[Khu vực] Rút gọn còn 823 records sau khi gom nhóm.
 [Danh mục] Rút gọn còn 2 records (tính trùng lặp thể loại).
Gộp 3 danh sách (Outer Join): Tổng cộng có 969 records.
Số record VỪA cùng [khu vực] VỪA cùng [danh mục]: 969
*** Top 10 địa điểm được khuyến nghị:
      - Hạng 44: POI ID = 1809062 | Tên POI = Diamond Superbowl | (Total Weight: 3.0, Số reviews toàn cục: 2.0)
      - Hạng 688: POI ID = 23300698 | Tên POI = Euphorea Salon And Spa - Bason Branch | (Total Weight: 2.0, Số reviews toàn cục: 302.0)
      - Hạng 153: POI ID = 6351606 | Tên POI = Asiana Link Travel | (Total Weight: 2.0, Số reviews toàn cục: 294.0)
      - Hạng 55: POI ID = 2037764 | Tên POI = Tháp Tài Chính Bitexco | (Total Weight: 2.0, Số reviews toàn cục: 287.0)
      - Hạng 147: POI ID = 5970625 | Tên POI = Temple Leaf Spa | (Total Weight: 2.0, Số reviews toàn cục: 270.0)
      - Hạng 528: POI ID = 15129760 | Tên POI = Phương Trang - FUTA Bus Lines | (Total Weight: 2.0, Số reviews toàn cục: 233.0)
      - Hạng 5: POI ID = 311103 | Tên POI = War Remnants Museum | (Total Weight: 2.0, Số reviews toàn cục: 210.0)
      - Hạng 470: POI ID = 13391755 | Tên POI = Private Daily Tours | (Total Weight: 2.0, Số reviews toàn cục: 175.0)
      - Hạng 40: POI ID = 1746272 | Tên POI = Les Rives Authentic River Experience | (Total Weight: 2.0, Số reviews toàn cục: 168.0)
      - Hạng 207: POI ID = 7339849 | Tên POI = Temple Leaf Spa & Sauna | (Total Weight: 2.0, Số reviews toàn cục: 165.0)

      user_id     poi_id  rec_poi_id                   rec_poi_name
0      1253.0  1910195.0     1557134                     TNK Travel
1      1253.0  1910195.0     6351606             Asiana Link Travel
2      1253.0  1910195.0     2037764         Tháp Tài Chính Bitexco
3      1253.0  1910195.0     5970625                Temple Leaf Spa
4      1253.0  1910195.0    15129760  Phương Trang - FUTA Bus Lines
...       ...        ...         ...                            ...
1035    313.0  8290115.0     2037764         Tháp Tài Chính Bitexco
1036    313.0  8290115.0     5970625                Temple Leaf Spa
1037    313.0  8290115.0    15129760  Phương Trang - FUTA Bus Lines
1038    313.0  8290115.0      311103            War Remnants Museum
1039    313.0  8290115.0     6721127                     Kim Travel

[1040 rows x 4 columns]

In [44]:
# Trích xuất các tương tác thực tế (ground truth) từ tất cả đánh giá
df_true_interactions = df_reviews[['user_id', 'poi_id']]
df_true_interactions

       user_id    poi_id
0            1    311103
1            2    311103
2            3    311103
3            4    311103
4            5    311103
...        ...       ...
23943    21311  15129760
23944    21312  15129760
23945    21313  15129760
23946    21314  15129760
23947    21315  34514717

[23948 rows x 2 columns]

In [45]:
# Lấy tất cả các thực thể liên quan bằng cách gộp tương tác thực tế và thực thể kiểm tra theo user id
df_all_relevant = pd.merge(df_test, df_true_interactions, on=['user_id'], how='inner')
# Đổi tên cột poi_id_x thành poi_id và poi_id_y thành rec_poi_id
df_all_relevant = df_all_relevant.rename(columns={'poi_id_x': 'poi_id', 'poi_id_y': 'rec_poi_id'})
# Loại bỏ các dòng có poi_id trùng với rec_poi_id
df_all_relevant = df_all_relevant[df_all_relevant['poi_id'] != df_all_relevant['rec_poi_id']]
df_all_relevant = df_all_relevant.drop_duplicates()

df_all_relevant

      user_id   poi_id  rec_poi_id
0        1253  1910195    10005057
1        1253  1910195      317893
2        1253  1910195    10836601
3        1253  1910195     1830324
5        1253  1910195      550709
...       ...      ...         ...
1547      313  8290115      317896
1548      313  8290115      454974
1549      313  8290115      317893
1550      313  8290115     2414430
1551      313  8290115     1784754

[1448 rows x 3 columns]

In [46]:
# Lấy tất cả các thực thể gợi ý liên quan bằng cách gộp tương tác thực tế và tương tác gợi ý
df_retrived_relevant = pd.merge(df_all_relevant, df_all_retrieved, on=['user_id', 'poi_id', 'rec_poi_id'], how='inner')
df_retrived_relevant

    user_id    poi_id  rec_poi_id                              rec_poi_name
0       472    317896     2037764                    Tháp Tài Chính Bitexco
1      1020    317898     8290115                      Phố đi bộ Nguyễn Huệ
2      1229  10085046      317898                         Notre Dame Square
3       484   5505885      311087                          Chợ Bến Thành
4       484   5505885     8290115                      Phố đi bộ Nguyễn Huệ
..      ...       ...         ...                                       ...
84      181  10388517    10044301  Công ty cổ phần xe khách Phương Trang
85      181  10388517     9806390                         Bến xe Chợ Lớn
86      474   1809055     1809062                         Diamond Superbowl
87      484    311087     5505885                            Đường Bùi Viện
88      313   8290115     1784754                           Đường Đồng Khởi

[89 rows x 4 columns]

In [47]:
# Tính chỉ số độ chính xác (precision score)
relevant_retrieved = df_retrived_relevant.shape[0]
all_retrived = df_all_retrieved.shape[0]

precision = relevant_retrieved / all_retrived

print(f'Precision Score: {precision}')

Precision Score: 0.08557692307692308

In [48]:
# Tính chỉ số độ gọi lại (recall score)
relevant_retrieved = df_retrived_relevant.shape[0]
all_relevant = df_all_relevant.shape[0]

recall = relevant_retrieved / all_relevant
print(f'Recall Score: {recall}')

Recall Score: 0.06146408839779006

In [49]:
# Tính chỉ số độ phủ (coverage score)
num_recommended_pois = df_all_retrieved['rec_poi_id'].nunique()
num_all_pois = df_pois.shape[0]

coverage = num_recommended_pois / num_all_pois
print(f'Coverage Score: {coverage}')

Coverage Score: 0.059230306674684305

In [50]:
# Tính điểm F1 (F1 score)
f1 = (2 * precision * recall) / (precision + recall)
print(f'F1 Score: {f1}')

F1 Score: 0.07154340836012862

# Đóng kết nối driver

In [30]:
driver.close()